vuestorefront/magento2

- CONTRIBUTING.md
- LICENSE
> chore: added community files for GitHub

- packages/composables/src/composables/getters/productGetters.ts
- packages/theme/pages/Product.vue
fixed the Product.vue errors that were present on the browser console.
applied a new composeable getter to get the upsell products
there were some errors present on the browser console on the Product.vue
this pr were created to fix the errors present on the Product.vue page on the theme package.
locally running the packages
> fix(theme): fixed the Product.vue page rendering

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/custom.md
- .github/ISSUE_TEMPLATE/feature_request.md
- README.md
adding new issue templates to the repository so it fills the correct GitHub community standards
n/a
n/a
> chore: update issue templates

- README.md
- packages/theme/.env.example
Updated steps necessary for contributing as well as clarify some requirements for the project
Fixes #28
Wanted to reduce questions and enable more people to help with the project
These steps used to setup my local environment after help from @bloodf 
Updated Readme file
> chore: update README.md

- .github/workflows/release.yml
chore: fixed semantic-release action
> chore: fixed semantic-release action

- .github/workflows/gitflow.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
> chore: updated github actions

- .releaserc
> chore: updated .releaserc

- packages/api-client/src/api/relatedProduct/relatedProductQuery.graphql
- packages/api-client/src/api/upsellProduct/upsellProductsQuery.graphql
- packages/api-client/src/types/GraphQL.ts
- packages/composables/src/composables/getters/categoryGetters.ts
- packages/composables/src/composables/getters/productGetters.ts
- packages/composables/src/helpers/htmlDecoder.ts
- packages/theme/components/MyAccount/ProfileUpdateForm.vue
fixes the displays of the upsell products and related products, and fixes the display of product name and category name with HTML entity.
Fixed the password request modal not being closed when clicked on the close icon.
fix the related issue in the query for related products and upsell products #23
fixed the password request modal on ProfileUpdateForm.vue modal not closing
added HTML decoder for titles in a category name and product name
locally tested
> refactor: upsell and related products listing and product labeling

- packages/api-client/package.json
- packages/api-client/src/api/relatedProduct/relatedProductQuery.graphql
- packages/api-client/src/api/upsellProduct/upsellProductsQuery.graphql
- packages/api-client/src/types/GraphQL.ts
- packages/composables/package.json
- packages/composables/src/composables/getters/categoryGetters.ts
- packages/composables/src/composables/getters/productGetters.ts
- packages/composables/src/helpers/htmlDecoder.ts
- packages/theme/components/MyAccount/ProfileUpdateForm.vue
- packages/theme/package.json
chore: release version 1.0.0-beta.4.1
> chore: release version 1.0.0-beta.4.1

- packages/api-client/package.json
- packages/api-client/src/fragments/productFragment.graphql
- packages/api-client/src/types/GraphQL.ts
- packages/composables/package.json
- packages/theme/package.json
- packages/theme/pages/Home.vue
> chore: release 1.0.0-beta.5

- scripts/lib/publishPackages.js
- scripts/publish.js
chore: release version 1.0.0-beta.7
> chore: release version 1.0.0-beta.7

- .github/workflows/publish.yml
- .npmrc
- packages/api-client/package.json
- packages/composables/package.json
- packages/theme/package.json
- scripts/lib/publishPackages.js
- yarn.lock
chore: release version 1.0.0-beta.8
> chore: release version 1.0.0-beta.8

- packages/api-client/src/api/relatedProduct/relatedProductQuery.graphql
- packages/api-client/src/api/upsellProduct/upsellProductsQuery.graphql
- packages/api-client/src/fragments/configurableProductOptionsFragment.graphql
removed non-default fields on GraphQL queries
> fix(api-client): removed non-default fields on GraphQL queries

- .github/workflows/publish.yml
- scripts/.npmrc
chore: release 1.0.0-beta.9
- `api-client`
- Removed non-default fields on GraphQL queries
- `general`
- Some issues related to release CICD process
- Composeable and theme imports of new methods
- `theme`
- Removed unused nuxt route
> fix: publishing process on CICD

- .github/workflows/publish.yml
> chore: added .npmrc copying scripts

- .github/workflows/publish.yml
- scripts/.npmrc
> fix: updated github actions to fix NPM publishing

- package.json
`api-client`
- created **country** API method
- created **getAvailableCustomerPaymentMethod** API method
- created **getAvailableCustomerShippingMethod** API method
- created **getAvailablePaymentMethod** API method
- created **getAvailableShippingMethod** API method
- added missing API methods to export
- added internal checkout flow with basic Magento payment system that doesn't require integrations
`composables`
- added MyAccount shipping and billing address manipulation
- added internal checkout flow with basic Magento payment system that doesn't require integrations
- created **useCountrySearch** factory and composable to load and search on Magento for country and region information
- created **useExternalCheckout** factory and composable to handle the external checkout process
- …
> chore: release version 1.0.0-beta.10

- .github/workflows/gitflow.yml
- .github/workflows/publish.yml
> chore: updated package publication github actions

- packages/theme/pages/MyAccount.vue
updated MyAccount.vue page to fix the MyProfile.vue component
Closes #90
> refactor(theme): fixed MyProfile.vue import on MyAccount.vue page

- packages/api-client/package.json
- packages/composables/package.json
- packages/theme/package.json
`api-client`
- added the `createProductReview` API method
- added the `customerProductReview` API method
- updated the `productReview` API method to return the product name and uid
- added `subscribeEmailToNewsletter` mutation and method
`composables`
- added to the `useReview` new methods for _loadCustomerReviews_ and _loadReviewMetadata_
- created the `useReviewFactory` from the core to add new functionalities
- added `useNewsletter` composable
- added `useNewsletterFactory` composable factory
`theme`
- added `ProductAddreviewForm.vue` component to be the product review form
- added `MyReviews.vue` page to show the user created reviews, under _MyAccount_
- added `MyNewsletter.vue` page
`api-client`
- updated `createCustomer` method typing
- fixed `customer` method GraphQL query
- …
> chore: release version 1.0.0-beta.14

- packages/composables/src/composables/useFacet/_utils.ts
- packages/composables/src/composables/useFacet/index.ts
- packages/theme/pages/Category.vue
Adds filter faceting to the category page
I have implemented the faceting featured and tested based on price, color and size
Closes issue #20 
Required to as part of the roadmap to production ready
Manually tested functionality in the browser. Automated tests still need to be written
> feat(theme): adds filter aggregation to the category page

- packages/composables/src/composables/useFacet/_utils.ts
- packages/theme/middleware.config.js
- packages/theme/nuxt.config.js
- packages/theme/pages/Category.vue
fixed the facets filter on Category.vue and the facetsGetters
locally tested
> fix: fixed facet filtering on Category.vue and facetsGetters

- packages/theme/components/Checkout/VsfShippingProvider.vue
> fix(theme): fixed code import from /src

- packages/composables/src/composables/useBilling/index.ts
> fix(composable) fix bug set billing address not working

- packages/api-client/src/api/configurableProductDetail/index.ts
- packages/api-client/src/api/createCustomer/index.ts
- packages/api-client/src/api/customerProductReview/index.ts
- packages/api-client/src/api/generateCustomerToken/index.ts
- packages/api-client/src/api/getAvailableCustomerPaymentMethods/index.ts
- packages/api-client/src/api/getAvailableCustomerShippingMethods/index.ts
- packages/api-client/src/api/getAvailablePaymentMethods/index.ts
- packages/api-client/src/api/getAvailableShippingMethods/index.ts
- packages/api-client/src/api/getCustomerAddresses/index.ts
- packages/api-client/src/api/productDetail/index.ts
- packages/api-client/src/api/productReview/index.ts
- packages/api-client/src/api/products/index.ts
- packages/api-client/src/api/relatedProduct/index.ts
- packages/api-client/src/api/upsellProduct/index.ts
- packages/theme/components/CartSidebar.vue
- packages/theme/components/Notification.vue
- packages/theme/composables/useUiNotification/index.ts
`theme`
- added NotificationUi to CartSidebar when removing products
`api-client`
- added better error handling
> feat: added Notification UI on CartSidebar

- packages/api-client/src/api/cmsBlocks/cmsBlocks.ts
- packages/api-client/src/api/cmsBlocks/index.ts
- packages/api-client/src/api/index.ts
- packages/api-client/src/index.ts
- packages/api-client/src/types/API.ts
- packages/api-client/src/types/GraphQL.ts
- packages/composables/src/composables/useContent/index.ts
- packages/composables/src/factories/useContentFactory.ts
- packages/composables/src/types/composables.ts
- packages/theme/components/ContentBlock.vue
- packages/theme/components/ContentBlocks.vue
- packages/theme/helpers/hooks/useVueRouter.ts
- packages/theme/pages/Page.vue
- packages/theme/routes.js
`api-client`
- added `cmsBlocks` method
`composables`
- added `loadBlocks` methods to the `useContent` composable
- added `blocks` to the `useContent` composable
`theme`
- added `ContentBlock` and `ContentBlocks` components
`theme`
- fixed the `cmsPage` content loading
- added the `cmsPage` routing system
> feat: added cmsBlocks and fixed cmsPage

- .github/ISSUE_TEMPLATE/1.bug-report.yml
- .github/workflows/gitflow.yml
> chore: fixed 1.bug-report.yml

- packages/composables/src/composables/getters/categoryGetters.ts
- packages/theme/package.json
- packages/theme/pages/Category.vue
- yarn.lock
`composables`
- fixed categoryGetters.ts buildTree method filtering
`theme`
- fixed how sidebar category is filtered
`theme`
- updated @storefront-ui/vue to 0.10.8
closes #138
closes #139
> fix: fixes the categories sidebar and pagination in Category.vue page

- packages/api-client/src/api/createCustomer/index.ts
- packages/api-client/src/api/generateCustomerToken/index.ts
- packages/composables/src/composables/useUser/index.ts
Now responses from createCustomerV2 and generateCustomerToken mutations are handled properly: server errors are still handled as server errors and data errors (wrong password, existing email) messages are proceeded and displayed to FE.
https://devdocs.magento.com/guides/v2.4/graphql/mutations/create-customer-v2.html
https://devdocs.magento.com/guides/v2.4/graphql/mutations/generate-customer-token.html
https://github.com/vuestorefront/magento2/issues/40
1. Register new customer with available email
2. Register new customer with already taken email
3. Log in with correct customer credentials
4. Log in with wrong customer credentials
5. Make M2 unresponsive and try to log in / register
> feat: Improve login and register dialogs errors

- packages/api-client/src/api/configurableProductDetail/configurableProductDetailQuery.ts
- packages/composables/src/composables/useProduct/index.ts
- packages/theme/pages/Product.vue
This PR does the fix for https://github.com/vuestorefront/magento2/issues/133 and improves a bit https://github.com/vuestorefront/magento2/issues/134 .
Idea is to query product price in `variant` property (which actually returns SimpleProduct type : https://devdocs.magento.com/guides/v2.4/graphql/interfaces/configurable-product.html#ConfigurableProductOptionsSelection ) and merge it with product. 
Initially it wasn't merged and calculation was done in getters. But points to chose this solution are:
1. We should update not just price, but also, for example, name and any other fields which are configured from magento to be different in Configurable and Variant products. ATM it's just a concept, but if it will work with no problems, we would need to add more fields we query in `variant` …
> fix: update product price and other properties on variant selection

- packages/composables/src/composables/getters/cartGetters.ts
- packages/theme/components/CartSidebar.vue
- packages/theme/components/Checkout/CartPreview.vue
- packages/theme/lang/en.js
- packages/theme/pages/Checkout/Payment.vue
This PR fixes discount displaying
https://github.com/vuestorefront/magento2/issues/145
1. Add product with discount to basket
2. Observe basket overlay
3. Observe order summary sidebar on checkout steps
4. Observe payment step
> fix: discount displaying 

- .czrc
- .github/workflows/docs-deployment.yaml
- packages/composables/src/composables/getters/cartGetters.ts
- packages/theme/components/CartSidebar.vue
I've added the possibility to get product link from cart sidebar
https://github.com/vuestorefront/magento2/issues/154
On cart sidebar, it was not possible to go on the product page of your cart item
- Add a product to your cart
- On cart side bar, click on product title
- You should see product page
> refactor(theme): add product link to cart items on cart sidebar

- .github/workflows/gitflow.yml
- packages/api-client/src/api/index.ts
- packages/api-client/src/api/requestPasswordResetEmail/index.ts
- packages/api-client/src/api/resetPassword/index.ts
- packages/api-client/src/api/resetPassword/resetPassword.ts
- packages/api-client/src/index.ts
- packages/api-client/src/types/API.ts
- packages/api-client/src/types/GraphQL.ts
- packages/composables/src/composables/getters/forgotPasswordGetters.ts
- packages/composables/src/composables/useForgotPassword/index.ts
- packages/composables/src/composables/useUser/index.ts
- packages/composables/src/factories/useForgotPasswordFactory.ts
- packages/composables/src/types/composables.ts
- packages/theme/components/AppHeader.vue
- packages/theme/components/LoginModal.vue
- packages/theme/pages/Category.vue
- packages/theme/pages/MyAccount/AddressesDetails.vue
- packages/theme/pages/MyAccount/MyNewsletter.vue
- packages/theme/pages/MyAccount/MyProfile.vue
- packages/theme/pages/MyAccount/MyReviews.vue
- packages/theme/pages/MyAccount/MyWishlist.vue
- packages/theme/pages/MyAccount/OrderHistory.vue
- packages/theme/pages/Product.vue
- packages/theme/pages/ResetPassword.vue
- packages/theme/routes.js
`composeables`
- created factory for `useForgotPassword`
`theme`
- added page for user resetting password
`composeables`
- fixed user not being able to update newsletter configuration (fixes #159)
- applied rules for `useForgotPasswordGetters`
`theme`
- added Ui notification on user updating information (closes #161 #160)
`repository`
- fixed gitflow action
closes #159 #160 #161
> fix: fixed user password reset and resolved other minor issues

- packages/composables/src/composables/getters/productGetters.ts
- packages/composables/src/helpers/htmlDecoder.ts
- packages/theme/components/Products/BundleProductSelector.vue
- packages/theme/components/Products/GroupedProductSelector.vue
- packages/theme/components/SearchResults.vue
- packages/theme/pages/Product.vue
`theme`
- fixed wishlist icon appearing in the search result (#173)
- fixed not showing loader in the product page
- removed the GroupedProduct to a separated component
- fixed the GroupedProduct not displaying the correct price (#174)
closes #173 
closes #174
> fix(theme): fixed Product display and search result display

- packages/theme/pages/MyAccount/AddressesDetails.vue
If address is removed from UserAddressDetails the addresses list is reloaded
https://github.com/vuestorefront/magento2/issues/184
> fix(theme): reload addresses on remove

- packages/theme/components/MyAccount/AddressForm.vue
- packages/theme/pages/Checkout/Billing.vue
- packages/theme/pages/Checkout/Shipping.vue
`theme`
- removed minimal char amount in street fixes #232
> refactor(theme): removed minimal char amount in street fixes #232

- packages/api-client/src/api/changeCustomerPassword/index.ts
- packages/api-client/src/api/productDetail/index.ts
- packages/api-client/src/api/wishlist/wishlist.ts
- packages/api-client/src/types/API.ts
- packages/composables/src/composables/useFacet/_utils.ts
- packages/composables/src/composables/useProduct/index.ts
- packages/composables/src/composables/useUser/index.ts
- packages/composables/src/composables/useWishlist/index.ts
- packages/composables/src/getters/facetGetters.ts
- packages/theme/components/Category/CategorySidebarMenu.vue
- packages/theme/components/LoginModal.vue
- packages/theme/components/MyAccount/PasswordResetForm.vue
- packages/theme/components/MyAccount/ProfileUpdateForm.vue
- packages/theme/helpers/customer/regex.ts
- packages/theme/pages/Category.vue
- packages/theme/pages/Checkout/UserAccount.vue
- packages/theme/pages/MyAccount/MyProfile.vue
- packages/theme/pages/Product.vue
- packages/theme/pages/ResetPassword.vue
- yarn.lock
`theme`
- fix password RegExp (closes #238)
- fix category not displaying products (closes #236)
- fix customizable product not being able to add t o cart (closes #228)
- fix notification on password change (closes #231)
- fix over pagination (closes #239)
- fix filter product not showing result (closes #230)
- fix wishlist icon not showing for product card (closes #229)
- added no-fetch param to `CategorySidebarMenu.vue` to prevent souble API calls
> bugfix: closes #238 #236 #228 #231 #239 #230 #229

- packages/theme/components/LoginModal.vue
- packages/theme/helpers/customer/regex.ts
- packages/theme/pages/Checkout/UserAccount.vue
- packages/theme/pages/MyAccount/MyProfile.vue
- packages/theme/pages/ResetPassword.vue
> fix(theme): update customer password regex

- .github/workflows/deploy-vue-storefront-cloud.yml
> chore: changed variables from `secrets` to `env`

- .github/workflows/deploy-vue-storefront-cloud.yml
> chore: added missing buildargs

- packages/theme/pages/MyAccount/AddressesDetails.vue
- packages/theme/routes.js
Fix issue #256
Rework customer account navigation to address #256 issue
Bug #256
> fix(theme): 256 customer account - address creation navigation issue

- .github/workflows/deploy-vue-storefront-cloud.yml
> chore: changed variables from env to secrets

- .github/workflows/deploy-vue-storefront-cloud.yml
> chore: changed variables from `env` to `secrets`

- .github/workflows/deploy-vue-storefront-cloud.yml
Updated names of domains in CD.
> chore(deploy): changed environments names

- .github/workflows/conventional-pr-name.yml
> chore: fixes Conventional PR GH Action

- packages/theme/components/CurrencySelector.vue
- packages/theme/components/LocaleSelector.vue
- packages/theme/helpers/magentoConfig/handleChanges.ts
`theme`
- fix Vue Router error on store change resolve #304
> refactor(theme): fix Vue Router error on store change closes #304

- packages/theme/pages/MyAccount/OrderHistory.vue
`theme`
- fix `Start Shopping` button not redirecting closes #299
> refactor(theme): fix `Start Shopping` button closes #299

- package.json
- packages/composables/src/composables/useCart/index.ts
- packages/theme/components/Products/BundleProductSelector.vue
- packages/theme/nuxt.config.js
- packages/theme/package.json
- yarn.lock
Bundle options weren't rendered correctly. `onBeforeMount` hook caused an error with hydration. 
Besides, the GraphQL API expected that value of entered bundle option is a string, but the number was sent.
Moreover, I fixed some HTML validation errors and added `@nuxt/html-validator` package that helps to check validation errors on local env. 
`theme`
- fixed bundle product rendering
- fixed bundle product HTML validation issues
- fixed duplicates keys in bundle product options
`composables`
- a fixed type of bundle option entered value (from number to a string)
🚀 Features
`theme`
- added `@nuxt/html-validator` module
#310 
1. I opened bundle product (Sprite Yoga Companion Kit_
2. I checked that bundle options are rendering correctly
3. I changed some product options
4. I added the product …
> fix: fixed bundle products rendering and adding to cart

- CONTRIBUTING.md
Added Definition of Done to the CONTRIBUTING.md file
Closes #327
> docs(contributing): added Definition of Done to the CONTRIBUTING.md file

- packages/theme/package.json
Moved @nuxtjs/html validator to devDependencies
> chore: moved html-validator to dev dependencies

- docs/.vuepress/config.js
- docs/guide/environments.md
> docs(deployment): added information about environments to the documentation

- docs/.vuepress/config.js
- docs/guide/functional-catalog.md
Added functional catalog to the documentation
Closes #326 
#326
> docs: added functional catalog to the documentation

- packages/api-client/src/api/addBundleProductsToCart/index.ts
- packages/api-client/src/api/addConfigurableProductsToCart/index.ts
- packages/api-client/src/api/addDownloadableProductsToCart/index.ts
- packages/api-client/src/api/addProductToWishList/index.ts
- packages/api-client/src/api/addProductsToCart/index.ts
- packages/api-client/src/api/addSimpleProductsToCart/index.ts
- packages/api-client/src/api/addVirtualProductsToCart/index.ts
- packages/api-client/src/api/applyCouponToCart/index.ts
- packages/api-client/src/api/createCustomer/index.ts
- packages/api-client/src/api/createCustomerAddress/index.ts
- packages/api-client/src/api/createProductReview/index.ts
- packages/api-client/src/api/removeCouponFromCart/index.ts
- packages/api-client/src/api/removeItemFromCart/index.ts
- packages/api-client/src/api/removeProductsFromWishlist/index.ts
- packages/api-client/src/api/setBillingAddressOnCart/index.ts
- packages/api-client/src/api/setGuestEmailOnCart/index.ts
- packages/api-client/src/api/setPaymentMethodOnCart/index.ts
- packages/api-client/src/api/setShippingAddressesOnCart/index.ts
- packages/api-client/src/api/setShippingMethodsOnCart/index.ts
- packages/api-client/src/api/updateCustomer/index.ts
I found the  issue when I tried to add a product to the cart, and after investigation I realized that in all mutations there was something like this: 
````
variables: { input }
````
In terms of adding to cart that causes an error because GraphQL expected input like this: 
````
variables: { cartId, cartiItems }
````
but got 
```
variables: { input: { cartId, cartItems }}
```
the issue is fixed for all mutations.
> fix(api-client): fixed api-client mutations missing variables issue

- .vuestorefrontcloud/docker/Dockerfile
- Fixed build issue (looks like a new yarn version does no support `--network-concurrency` flag
- Changed Node version in Dockerfile from 14 to 16
> build: fixed build issues related to new yarn version

- packages/composables/src/composables/useAddresses/index.ts
- packages/composables/src/composables/useBilling/index.ts
- packages/composables/src/composables/useCart/index.ts
- packages/composables/src/composables/useCategory/index.ts
- packages/composables/src/composables/useCategorySearch/index.ts
- packages/composables/src/composables/useConfig/index.ts
- packages/composables/src/composables/useContent/index.ts
- packages/composables/src/composables/useCountrySearch/index.ts
- packages/composables/src/composables/useCurrency/index.ts
- packages/composables/src/composables/useFacet/index.ts
- packages/composables/src/composables/useForgotPassword/index.ts
- packages/composables/src/composables/useGetShippingMethods/index.ts
- packages/composables/src/composables/useGuestUser/index.ts
- packages/composables/src/composables/useMakeOrder/index.ts
- packages/composables/src/composables/useNewsletter/index.ts
- packages/composables/src/composables/usePaymentProvider/index.ts
- packages/composables/src/composables/useProduct/index.ts
- packages/composables/src/composables/useRelatedProducts/index.ts
- packages/composables/src/composables/useReview/index.ts
- packages/composables/src/composables/useShipping/index.ts
- packages/composables/src/composables/useShippingProvider/index.ts
- packages/composables/src/composables/useStore/index.ts
- packages/composables/src/composables/useUpsellProducts/index.ts
- packages/composables/src/composables/useUrlResolver/index.ts
- packages/composables/src/composables/useUser/index.ts
- packages/composables/src/composables/useUserBilling/index.ts
- packages/composables/src/composables/useUserOrder/index.ts
- packages/composables/src/composables/useUserShipping/index.ts
- packages/composables/src/composables/useWishlist/index.ts
`composables`
- fixed `customQuery` not being called
> refactor(composables): fixed `customQuery` not being called

- packages/theme/pages/Category.vue
> fix(theme): fix flashing category page

- packages/theme/pages/MyAccount.vue
Fixes #300 
All nav items and titles are aligned correctly
> fix(theme): my account align titles to nav items

- packages/composables/src/composables/useFacet/index.ts
Fix useFacet(...) customQuery implementation 
#412
> fix: useFacet(...) customQuery implementation

- packages/theme/components/SearchResults.vue
Update all non-localized :link bindings in templates
#405 
bugfix
- visiting related pages
-
> fix(theme): update localisation for all :link bindings

- packages/theme/nuxt.config.js
- packages/theme/package.json
- yarn.lock
> chore(theme): removed html-validator

- packages/theme/pages/MyAccount/AddressesDetails.vue
#417 
Bugfixing
Visit Customer Account -> Address Details tab
-
> fix(theme): fix 404 issue when redirecting to address details page

- packages/api-client/src/index.server.ts
Update default mutation error handling for apollo client so data can be properly handled regardless of errors
#235
> fix(api-client): update default mutation error handling for apollo client

- packages/theme/components/CurrencySelector.vue
- packages/theme/components/TopBar.vue
- packages/theme/nuxt.config.js
Enable the currency switcher on the `TopBar.vue` component, and add the configuration to prevent the cookie from auto changing.
closes #355  
This feature has been tested locally, and previously tested.
> refactor(theme): enable the currency switcher on `TopBar.vue`

- packages/theme/components/AppHeader.vue
Remove not necessary duplicated cart loading actions
#411 
Performance, bugfix
I simply put console log inside a cartload method to capture all loading occurrences, I am not sure though how to effectively test it on the front
> fix(theme): remove redundant cart load actions

- packages/composables/src/composables/useUser/index.ts
Clearing cart data on customer logout.
#406 
Bugfix
1. Log in as a customer
2. Add something to cart
3. Log out
4. Observe that your cart is cleared
> fix(composable): fix clearing cart on customer logout

- .eslintrc.js
- packages/composables/src/factories/useStoreFactory.ts
- packages/theme/components/CurrencySelector.vue
- packages/theme/composables/useMagentoConfiguration.ts
- packages/theme/layouts/default.vue
- update request to non-blockin (remove unnecessary await keywords)
- add LazyHydration on homepage
- move load config from onSSR to onMounted
-
Performance improvement
-
> perf(general): add performance improvement changes

- .eslintrc.js
- packages/composables/src/factories/useStoreFactory.ts
- packages/theme/components/CurrencySelector.vue
- packages/theme/composables/useMagentoConfiguration.ts
- packages/theme/layouts/default.vue
Reverts vuestorefront/magento2#471
> chore: revert "perf(general): add performance improvement changes"

- packages/theme/pages/Product.vue
added horizontal padding to the product page and reduced the spacing between the image slider and the product description.
#307
> fix(theme): fixed product layout tablet

- packages/theme/pages/Checkout.vue
added spacing on the left and right of the checkout page
#308
> fix(theme): added spacing on the left and right of the checkout page

- packages/theme/pages/Checkout.vue
- packages/theme/pages/Checkout/Payment.vue
Added padding to the checkout page, aligned the terms and condition checkbox and added bottom margin to the total price.
#309
> fix(theme): fixed payment setup style discrepancies

- packages/theme/lang/de.js
- packages/theme/lang/en.js
- packages/theme/pages/MyAccount/MyReviews.vue
Added "You have submitted no reviews" if there are no reviews.
#302
> fix(theme): fixed review page is empty if there are no reviews

- packages/theme/components/Products/BundleProductSelector.vue
Added paddings and margins to fix visual discrepancies of the bundle products.
#298
> fix(theme): product bundle visual issue

- packages/theme/components/LoginModal.vue
- packages/theme/lang/de.js
- packages/theme/lang/en.js
Add $t function for all errors in the login modal.
-
-
Open login modal, perform a few invalid actions, and observe the result.
> fix(theme): update login modal to handle translations

- packages/theme/pages/Product.vue
https://github.com/vuestorefront/magento2/issues/439
https://vsf.atlassian.net/browse/M2-85
https://www.loom.com/share/49c029c988184980a1045de2b29aba86
> fix: disable ATC button while new product configuration is being loaded

- .vuestorefrontcloud/docker/nuxt.config.additional.js
Disabled Recaptcha on our environments
> chore: disabled rechaptcha by default

- .vuestorefrontcloud/docker/nuxt.config.additional.js
> build: removed recaptcha from deployment config

- packages/composables/src/composables/useFacet/index.ts
useFacets composable was ignoring customQueries, here is the fix for that
#533 
bugfix
- add custom query for products and check if data returned on the category page includes custom fields
-
> fix(composable): update useFacets to work with a customQueries

- packages/composables/src/composables/useProduct/index.ts
- packages/theme/components/RelatedProducts.vue
- packages/theme/components/UpsellProducts.vue
https://github.com/vuestorefront/magento2/issues/263
https://vsf.atlassian.net/browse/M2-41
https://www.loom.com/share/8a04609683404858b375069ec414895d
> fix: configurable product should work when only one attribute is used

- packages/theme/components/AppHeader.vue
https://github.com/vuestorefront/magento2/issues/303
https://vsf.atlassian.net/browse/M2-32
https://www.loom.com/share/4b0c83becba5445aaf18d8e9bbee8cce
> fix: the ability to close quick search using the keyboard

- packages/theme/components/InstagramFeed.vue
https://github.com/vuestorefront/magento2/issues/297
https://vsf.atlassian.net/browse/M2-36
> fix: fixed InstagramFeed component

- packages/theme/components/AppHeader.vue
https://github.com/vuestorefront/magento2/issues/306
https://vsf.atlassian.net/browse/M2-31
> fix: changed header spacing

- docs/guide/recaptcha.md
- packages/theme/components/AppHeader.vue
- packages/theme/layouts/default.vue
- packages/theme/package.json
- yarn.lock
Added lazy load to improve performance a little bit. 
Improve performance
Tested on local env
> refactor: added loazy loaded components for default layout and app header

- packages/theme/components/InstagramFeed.vue
- packages/theme/components/MobileStoreBanner.vue
added lazy loading for offscreen images on homepage
Improve performance
> refactor(theme): added lazy loading for offscreen images on homepage

- packages/theme/nuxt.config.js
- packages/theme/package.json
- yarn.lock
add @nuxt/pinia module to manage app state
-
refactoring
-
> refactor(theme): add @nuxt/pinia module to manage app state

- packages/theme/plugins/dompurify.ts
fix dompurify arguments injection
-
-
Build package and check if there is no error on pages using dompurify plugin, eg CMS page.
> fix(theme): fix dompurify arguments injection

- packages/theme/components/BottomNavigation.vue
- packages/theme/components/MobileMenuSidebar.vue
- packages/theme/lang/de.js
- packages/theme/lang/en.js
https://github.com/vuestorefront/magento2/issues/294
https://vsf.atlassian.net/browse/M2-38
> feat: mobile menu

- packages/composables/src/composables/useExternalCheckout/index.ts
- packages/composables/src/factories/useExternalCheckoutFactory.ts
- packages/theme/components/CartSidebar.vue
- packages/theme/composables/index.ts
- packages/theme/composables/useExternalCheckout/index.ts
- packages/theme/composables/useExternalCheckout/useExternalCheckout.d.ts
- mark composable useExternalCheckout as deprecated
- mark factory useExternalCheckout as deprecated
- move composable to theme module
- changed initializeCheckout method binding in CartSidebar
> refactor: refactored useExternalCheckout composable

- docs/.vuepress/config.js
fix the duplicated testing menu item on docs
> docs: fix duplicated menu item

- packages/api-client/src/types/context.ts
- packages/composables/src/composables/useWishlist/index.ts
- packages/composables/src/factories/useWishlistFactory.ts
- packages/theme/components/AppHeader.vue
- packages/theme/components/LoginModal.vue
- packages/theme/components/ProductsCarousel.vue
- packages/theme/components/SearchResults.vue
- packages/theme/components/WishlistSidebar.vue
- packages/theme/composables/index.ts
- packages/theme/composables/useWishlist/helpers.ts
- packages/theme/composables/useWishlist/index.ts
- packages/theme/composables/useWishlist/useWishlist.d.ts
- packages/theme/pages/Category.vue
- packages/theme/pages/MyAccount/MyWishlist.vue
- packages/theme/pages/Product.vue
- packages/theme/stores/customer.ts
- refactored useWishlist to use pinia store
- make useWishlist and useWishlistFactory from composables deprecated
> refactor: useWishlist

- packages/composables/nuxt/plugin.js
- packages/composables/src/composables/useCurrency/index.ts
- packages/composables/src/factories/useCurrencyFactory.ts
- packages/theme/components/CurrencySelector.vue
- packages/theme/components/StoreSwitcher.vue
- packages/theme/composables/index.ts
- packages/theme/composables/useConfig/index.ts
- packages/theme/composables/useConfig/useConfig.d.ts
- packages/theme/composables/useCurrency/index.ts
- packages/theme/composables/useCurrency/useCurrency.d.ts
- packages/theme/composables/useMagentoConfiguration.ts
- packages/theme/composables/useStore/index.ts
- packages/theme/composables/useStore/useStore.d.ts
- packages/theme/stores/config.ts
refactor(theme): refactor useCurrency composable
BREAKING CHANGES:
- mark useCurrency as a deprecated in composables module
-  add refactored and lightweight useCurrency in theme with usage of pinia store management
> refactor(theme):  M2 155. refactor useCurrency composable

- packages/theme/components/AppHeader.vue
- packages/theme/components/BottomNavigation.vue
- packages/theme/components/StoreSwitcher.vue
Fix for #546 
Fix for #547 
Small fixes on mobile devices
Fixes the missing currency-switcher on mobile. On mobile, the store name is removed for extra space.
Fixes the login modal, it will only show when the user isn't authenticated.
> fix: small fixes for mobile

- packages/composables/src/composables/useUser/index.ts
- packages/theme/components/AppHeader.vue
- packages/theme/components/BottomNavigation.vue
- packages/theme/components/CartSidebar.vue
- packages/theme/components/LoginModal.vue
- packages/theme/components/MyAccount/ProfileUpdateForm.vue
- packages/theme/components/ProductAddReviewForm.vue
- packages/theme/components/ProductsCarousel.vue
- packages/theme/components/SearchResults.vue
- packages/theme/components/WishlistSidebar.vue
- packages/theme/composables/index.ts
- packages/theme/composables/useUser/index.ts
- packages/theme/composables/useUser/useUser.d.ts
- packages/theme/helpers/customer/userDataGenerator.ts
- packages/theme/pages/Category.vue
- packages/theme/pages/Checkout/Billing.vue
- packages/theme/pages/Checkout/Shipping.vue
- packages/theme/pages/Checkout/UserAccount.vue
- packages/theme/pages/MyAccount.vue
- packages/theme/pages/MyAccount/MyNewsletter.vue
- packages/theme/pages/MyAccount/MyProfile.vue
- packages/theme/pages/Product.vue
- packages/theme/stores/customer.ts
- make useUser from composables depracated
- added the new useUser composable in theme
- updated templates to use the new composables
Tested manually on local
> refactor: useUser

- packages/theme/components/AppHeader.vue
- packages/theme/components/Category/CategorySidebarMenu.vue
- packages/theme/components/MobileMenuSidebar.vue
- packages/theme/composables/index.ts
- packages/theme/composables/useCategory/index.ts
- packages/theme/composables/useCategory/useCategory.d.ts
- packages/theme/pages/Category.vue
- refactored useCategory composable
- added useNavigation composable
- added navigation pinia store
> refactor: refactored useCategory composable

- packages/composables/src/composables/useCategorySearch/index.ts
- packages/composables/src/factories/useCategorySearchFactory.ts
- packages/theme/components/AppHeader.vue
- packages/theme/composables/index.ts
- packages/theme/composables/useCategorySearch/index.ts
- packages/theme/composables/useCategorySearch/useCategorySearch.d.ts
- refactored useSearchCategory
> refactor: refactored useCategorySearch

- packages/composables/src/composables/useContent/index.ts
- packages/composables/src/factories/useContentFactory.ts
- packages/theme/components/ContentBlocks.vue
- packages/theme/composables/index.ts
- packages/theme/composables/useContent/commands/loadBlocksCommand.ts
- packages/theme/composables/useContent/commands/loadContentCommand.ts
- packages/theme/composables/useContent/index.ts
- packages/theme/composables/useContent/useContent.d.ts
- packages/theme/pages/Page.vue
BREAKING CHANGE: - mark useContent as deprecated, implement useContent in theme package
> refactor(theme): refactor useContent composable

- packages/theme/composables/useMagentoConfiguration.ts
> fix: load config SSR issues

- packages/theme/tsconfig.json
- tsconfig.base.json
Updated tsconfig value to es2019
> build(tsconfig): changed target in tdconfig files from es5 to es2019

- packages/theme/layouts/default.vue
> perf(theme): lazy load loginModal

- .github/workflows/merge-release.yml
> build(gh actions): fixed merge-release GH action

- packages/theme/nuxt.config.js
Before this change, it was not possible to clear Redis cache.
> fix(redis): added missing redis config

- docs/index.md
> docs: updated docs main information

- packages/theme/components/AppHeader.vue
- packages/theme/components/Header/SearchBar/SearchBar.vue
- packages/theme/components/Header/SearchBar/SearchResults.vue
- move search bar component to components/Header
- remove unused code and watchers
-
refactoring
-
> refactor: move search form to separate component

- packages/theme/nuxt.config.js
Before: Redis was enabled always even if you had 'false' in the env variable.
After: we converted string to bool, and configuration works properly then.
> fix(config): fixed redis__enabled varaible binding

- packages/api-client/src/api/cart/index.ts
- packages/api-client/src/api/cartTotalQty/cartTotalQty.ts
- packages/api-client/src/api/cartTotalQty/index.ts
Fix `[GraphQL error]: Message: Required parameter "cart_id" is missing, Location: [column: 3, line: 2], Path: cart`
-
bugfix
-
> fix(api): fix cart_id graphql error

- packages/theme/components/CartSidebar.vue
https://github.com/vuestorefront/magento2/issues/609
https://vsf.atlassian.net/browse/M2-194
> fix: centered empty cart text and image

- packages/theme/components/MyAccount/AddressForm.vue
https://github.com/vuestorefront/magento2/issues/610
https://vsf.atlassian.net/browse/M2-195
> fix(theme): [My Account] Aligned State/Province input

- packages/theme/components/CartSidebar.vue
removed margin and added translate to center modal
https://vsf.atlassian.net/browse/M2-202
> chore(theme): product removal confirmation out of viewport

- packages/theme/pages/Category.vue
add pagination on the category mobile view
#616 
Improvement
-
> feat(theme): add pagination on the category mobile view

- packages/theme/pages/Product.vue
https://github.com/vuestorefront/magento2/issues/607
https://vsf.atlassian.net/browse/M2-192
> fix(theme): [Product] Fixed Additional information tab

- packages/theme/components/StoreSwitcher.vue
- packages/theme/composables/useApi/index.ts
- packages/theme/nuxt.config.js
- optimized chunks
- disabled links prefetching for better performance
- from now undefined.webp flag is not rendered anymore in store switcher
- from now storefront, does not send requests to Magento API with `store: undefined` header that caused error response with 500 code
> refactor: optimized build, fixed small bugs

- packages/theme/components/AppHeader.vue
- packages/theme/components/HeaderLogo.vue
- fixed mobile/desktop navigation caching issues
> refactor(theme): fixed cache issues

- README.md
> chore: add #techforukraine

- packages/theme/README.md
> chore: updated readme

- packages/theme/components/Category/CategoryNavbar.vue
- packages/theme/components/Category/CategorySidebar.vue
- packages/theme/components/Category/CmsContent.vue
- packages/theme/components/Category/EmptyResults.vue
- packages/theme/components/Category/categoryContent.gql.ts
- packages/theme/components/Category/enums/displayModesEnum.ts
- packages/theme/components/Category/useCategoryContent.ts
- packages/theme/composables/useApi/index.ts
- packages/theme/lang/de.js
- packages/theme/lang/en.js
- packages/theme/pages/Category.vue
refactor(theme): category page refactoring step-1
- separate category page and sidebar logic
- add resolving layput configuration on category page
- move navbar to a separate component
- add redis cache for the sidebar
- add empty results page
> refactor(theme): add components lazy import

- packages/theme/components/Category/CategorySidebar.vue
- packages/theme/components/Header/SearchBar/SearchBar.vue
- packages/theme/components/SkeletonLoader/SkeletonLoader.vue
- packages/theme/pages/Category.vue
I added a new basic SkeletonLoader component.
This is the first iteration, we must decompose category further.
-
-
-
> feat(theme): add basic skeleton loader component

- .husky/pre-commit
Fixed recommit hooks execution. 
Since git doesn't support running lint-staged in parallel with Lerna we need to run `precommit` commands synchronously.
> build: refactored precommit hooks execution

- packages/theme/pages/MyAccount/OrderHistory.vue
Correcting the heading alignment for the order history table.
https://vsf.atlassian.net/browse/M2-146
> fix(M2-146): correct desktop order history column alignment

- internals/eslint-import/package.json
- internals/eslint-jest/package.json
- internals/eslint-typescript/package.json
- internals/eslint-vue/package.json
- internals/eslint/package.json
- packages/api-client/package.json
- packages/composables/package.json
- packages/theme/package.json
> chore: updated packages versions

- packages/composables/src/getters/cartGetters.ts
- packages/theme/components/CartSidebar.vue
fix(theme): fix cart's product URL resolving for configurable products
I have tested a few conceptions like adding types to ProductInterface or changing composable and getters but this solution is the simplest one and makes the most sense to me.
#468
> fix(theme): fix cart's product url resolving for a configurable products

- packages/theme/components/CartSidebar.vue
- packages/theme/components/WishlistSidebar.vue
> fix(theme): remove redundant console logs

- packages/theme/pages/MyAccount.vue
Will clear vsf-checkout localStorage key upon logout
https://vsf.atlassian.net/browse/M2-105
Avoids showing previously entered information on checkout after logouts (presumably this might be another session).
> refactor(theme): clear local storage on logout

- README.md
- docs/guide/override-queries.md
Update the documentation of overriding queries, including:
1. Step-by-step example
2. Code example to be more precise and practical.
#701 
- Help other developers know how to get started with custom queries easily.
N/A
N/A
> docs: update documentation for override queries

- docs/.vuepress/config.js
Removed "performance" duplicated section from nav.
> docs: removed duplicated section from docs

- packages/theme/pages/Page.vue
- new composables implementation break that part of app
> fix(theme): fix broken cms page load

- packages/theme/modules/catalog/category/components/sidebar/CategorySidebar.vue
- packages/theme/modules/catalog/pages/default.vue
- improve skeleton for the category sidebar
-
-
> fix(theme): improve skeleton for the category sidebar

- packages/composables/src/composables/useNewsletter/index.ts
- packages/composables/src/factories/useNewsletterFactory.ts
- packages/theme/composables/useNewsletter/commands/updateSubscriptionCommand.ts
- packages/theme/composables/useNewsletter/enums/SubscriptionStatusesEnum.ts
- packages/theme/composables/useNewsletter/index.ts
- packages/theme/composables/useNewsletter/useNewsletter.d.ts
refactor useNewslettter composable
-
refactoring
-
> refactor(composable): refactor useNewslettter composable

- packages/composables/src/composables/useCurrency/index.ts
- packages/composables/src/composables/useExternalCheckout/index.ts
- packages/composables/src/composables/useFacet/index.ts
- packages/composables/src/composables/useForgotPassword/index.ts
- packages/composables/src/composables/useGuestUser/index.ts
- packages/composables/src/composables/useProduct/index.ts
- packages/composables/src/composables/useStore/index.ts
- packages/composables/src/composables/useUser/index.ts
- packages/composables/src/composables/useWishlist/index.ts
- packages/composables/src/factories/useCartFactory.ts
- packages/composables/src/factories/useCategorySearchFactory.ts
- packages/composables/src/factories/useConfigFactory.ts
- packages/composables/src/factories/useContentFactory.ts
- packages/composables/src/factories/useCurrencyFactory.ts
- packages/composables/src/factories/useExternalCheckoutFactory.ts
- packages/composables/src/factories/useForgotPasswordFactory.ts
- packages/composables/src/factories/useGuestUserFactory.ts
- packages/composables/src/factories/useStoreFactory.ts
- packages/composables/src/factories/useWishlistFactory.ts
- packages/theme/composables/index.ts
- packages/theme/composables/useProduct/commands/getProductDetailsCommand.ts
- packages/theme/composables/useProduct/commands/getProductListCommand.ts
- packages/theme/composables/useProduct/index.ts
- packages/theme/composables/useProduct/useProduct.d.ts
- packages/theme/helpers/product/productData.ts
- packages/theme/pages/Home.vue
- packages/theme/pages/Product.vue
- move useProduct composable to the theme package
- mark useProduct composable in composables package as deprecated
> refactor(composables): refactor useProduct composable

- docs/guide/override-queries.md
Fix the broken code block
#726
> docs: update override-queries.md

- packages/theme/layouts/default.vue
- packages/theme/nuxt.config.js
- packages/theme/package.json
- yarn.lock
https://vsf.atlassian.net/browse/M2-292
> refactor: optimize google fonts

- packages/theme/lang/de.js
- packages/theme/lang/en.js
- packages/theme/layouts/error.vue
- packages/theme/nuxt.config.js
- packages/theme/pages/Page.vue
- yarn.lock
- fixed 404 page
- fixed vee-validate compilation
https://vsf.atlassian.net/browse/M2-242
bug fixing
Tested on local env
> fix: fixed 404 page issues and my-account redirects for non-logged users

- packages/composables/src/composables/useAddresses/index.ts
- packages/composables/src/factories/useAddressesFactory.ts
- packages/theme/components/MyAccount/AddressForm.vue
- packages/theme/composables/index.ts
- packages/theme/composables/useAddresses/index.ts
- packages/theme/composables/useAddresses/useAddresses.d.ts
- packages/theme/pages/MyAccount/AddressesDetails.vue
- added the useAddresses composable to theme
- marked useAddresses composable from integration package depracated
- refactored AddressDetails.vue component
[M2-145](https://vsf.atlassian.net/browse/M2-245)
refactorization, improving performance and developer experience
tested on my local env in production mode
> refactor: refactored useAddresses

- packages/composables/src/composables/useMakeOrder/index.ts
- packages/theme/components/AppHeader.vue
- packages/theme/composables/index.ts
- packages/theme/composables/useMakeOrder/commands/placeOrderCommand.ts
- packages/theme/composables/useMakeOrder/index.ts
- packages/theme/composables/useMakeOrder/useMakeOrder.d.ts
- packages/theme/pages/Checkout/Payment.vue
- packages/theme/pages/Product.vue
- move composable to the Theme package
- mark composable as deprecated
-
refactoring
-
> refactor(composables): refactor useMakeOrder composable

- packages/composables/src/composables/useUpsellProducts/index.ts
- packages/composables/src/factories/useUpsellProductsFactory.ts
- packages/theme/components/UpsellProducts.vue
- packages/theme/composables/index.ts
- packages/theme/composables/useUpsellProducts/index.ts
- packages/theme/composables/useUpsellProducts/useUpsellProducts.d.ts
- packages/theme/pages/Product.vue
- added useUpsellProducts composable to theme
- made useUpsellProducts composable and factory from integration package depracated
- refactored UpsellProducts component
- fixed SSR issues on product page
[#256](https://vsf.atlassian.net/browse/M2-256)
refactorization, improving performance and developer experience
Tested on my local in production mode
> refactor(theme): refactored useUpsellProducts composable

- packages/composables/src/composables/useUrlResolver/index.ts
- packages/composables/src/factories/useUrlResolverFactory.ts
- packages/theme/composables/useUrlResolver.ts
- packages/theme/modules/catalog/pages/default.vue
- refactored useUrlResolver composable
refactorization, improving performance and developer experience
tested on my local on category pages
> refactor: refactored useUrlResolver

- packages/theme/composables/index.ts
- packages/theme/composables/useUserOrder/index.ts
- packages/theme/pages/MyAccount/OrderHistory.vue
- moved useUserOrder composable to theme
refactorization, improving the developer experience
tested on my local. I logged in as a customer and checked that orders in orders history are displaying correctly after factorization.
> refactor: refactored useUserOrder composable

- packages/theme/components/Header/SearchBar/SearchBar.vue
- refactored SearchBar component to use new useFacet and useCategorySearch composables
- added `lang="ts"` to the component
- fixed eslint errors
refactorization
tested on my local env. I tested the page header's search form
> refactor(theme): refactored SearchBar component to use new composables

- packages/composables/src/composables/useUserShipping/index.ts
- packages/theme/components/Checkout/UserShippingAddresses.vue
- packages/theme/composables/index.ts
- packages/theme/composables/useUser/index.ts
- packages/theme/composables/useUser/useUser.d.ts
- packages/theme/composables/useUserShipping/commands/createCustomerAddressCommand.ts
- packages/theme/composables/useUserShipping/commands/deleteCustomerAddressCommand.ts
- packages/theme/composables/useUserShipping/commands/updateCustomerAddressCommand.ts
- packages/theme/composables/useUserShipping/index.ts
- packages/theme/composables/useUserShipping/useUserShipping.d.ts
- packages/theme/composables/utils/mask.ts
- packages/theme/pages/Checkout/Shipping.vue
- move useUserShipping to the theme
- mark useUserShipping in composable package as deprecated
> refactor(composable): refactor useUserShipping

- .github/workflows/assing-pr-to-author.yml
- .github/workflows/conventional-pr-name.yml
- .github/workflows/test.yml
add concurrency control to GitHub actions
> chore: add concurrency control to GitHub actions

- packages/theme/components/CurrencySelector/CurrenciesModal.vue
- packages/theme/components/StoreSwitcher/StoresModal.vue
- packages/theme/composables/types.d.ts
- packages/theme/composables/useAddresses/index.ts
- packages/theme/composables/useConfig/useConfig.d.ts
- packages/theme/composables/useCurrency/useCurrency.d.ts
- packages/theme/composables/useMagentoConfiguration.ts
- packages/theme/composables/useStore/index.ts
- packages/theme/getters/_utils.ts
- packages/theme/getters/addressGetter.ts
- packages/theme/getters/cartGetters.ts
- packages/theme/getters/categoryGetters.ts
- packages/theme/getters/checkoutGetters.ts
- packages/theme/getters/facetGetters.ts
- packages/theme/getters/productGetters.ts
- packages/theme/getters/storeConfigGetters.ts
- packages/theme/getters/storeGetters.ts
- packages/theme/getters/userAddressesGetters.ts
- packages/theme/getters/userGetters.ts
- packages/theme/helpers/cart/addToCart.ts
- packages/theme/helpers/htmlDecoder.ts
- packages/theme/pages/ResetPassword.vue
- packages/theme/pages/__tests__/ResetPassword.spec.js
- packages/theme/stores/config.ts
- packages/theme/stores/customer.ts
- refactored CurrenciesModal to use new composable 
- refactored StoreSwitcher to use new composables
- refactored other components to use new composables
- refactored getters to use types from theme
> refactor: refactored types and composables to new ones from theme

- packages/composables/src/composables/useCountrySearch/index.ts
- packages/composables/src/factories/useCountrySearchFactory.ts
- packages/theme/components/MyAccount/AddressForm.vue
- packages/theme/composables/index.ts
- packages/theme/composables/types.d.ts
- packages/theme/composables/useCountrySearch/index.ts
- packages/theme/pages/Checkout/Billing.vue
- packages/theme/pages/Checkout/Shipping.vue
- refactored useCountrySearch composable
refactorization
tested on my local on address details page and checkout
> refactor: refactored useCountrySearch composable

- packages/theme/components/MyAccount/AddressForm.vue
- packages/theme/pages/MyAccount/AddressesDetails.vue
- fixed adding address on my account
- fixed removing address on my account
#765 #766
bugfixing
tested on my account:
1. log-in as a customer
2. go to address details
3. add a new address
4. delete address
> fix: fixed adding/removing address funcionality

- packages/theme/package.json
disabled nuxt modern mode
Nuxt modern mode is blocking CDN/Redis support for the integration.
> build: disabled nuxt modern mode

- packages/theme/nuxt.config.js
- disabled vsf/core sfui plugin and added transpiling of storefrontu-ui to the nuxt build config.
refactor, improving performance
tested using `yarn build` and `yarn start` commands
> refactor: disabled sfui core plugin

- packages/theme/components/AppHeader.vue
- packages/theme/components/ContentBlocks.vue
- packages/theme/components/WishlistSidebar.vue
- packages/theme/composables/types.d.ts
- packages/theme/composables/useWishlist/index.ts
- packages/theme/composables/useWishlist/useWishlist.d.ts
- packages/theme/nuxt.config.js
- packages/theme/pages/Checkout/UserAccount.vue
- packages/theme/pages/MyAccount/AddressesDetails.vue
- packages/theme/pages/MyAccount/MyNewsletter.vue
- packages/theme/pages/MyAccount/MyWishlist.vue
- removed onSSR hooks from our templates
- fixed broken my account page
refactorization, bugfixing
tested on my local, for logged-in and not logged customer
> refactor: replaced onSSR method calls wih Nuxt useAsync and useFetch hooks

- packages/theme/components/MyAccount/ProfileUpdateForm.vue
- packages/theme/pages/MyAccount.vue
- packages/theme/pages/MyAccount/MyNewsletter.vue
- packages/theme/pages/MyAccount/MyWishlist.vue
- packages/theme/pages/MyAccount/OrderHistory.vue
- fixed SfLink props issues
- fixed update personal data form submitting
- fixed breadcrumbs props issues
#676
bugfixing
tested on local on my account pages
> fix: fixed my account issues

- packages/theme/components/MyAccount/AddressForm.vue
- packages/theme/pages/MyAccount/MyNewsletter.vue
- fixed submitting address form
- fixed submitting changes on a newsletter subscription
bugfixing
tested on local environment
> fix: fixed my account buttons

- packages/theme/components/AppHeader.vue
- packages/theme/components/MobileMenuSidebar.vue
- packages/theme/composables/useCategory/index.ts
- packages/theme/composables/useCategory/useCategory.ts
Refactored useCategory composable for better DX experience
> refactor: refactored useCategory for better dx experience

- packages/theme/modules/catalog/category/components/breadcrumbs/CategoryBreadcrumbs.vue
- packages/theme/modules/catalog/category/components/sidebar/CategorySidebar.vue
- packages/theme/modules/catalog/category/components/sidebar/MobileCategorySidebar/MobileCategorySidebar.vue
- packages/theme/modules/catalog/category/helpers/index.ts
- packages/theme/modules/catalog/pages/category.vue
- packages/theme/plugins/i18n.ts
- Add new CategoryBreadcrumbs component. It's logic is based on what's in MobileCategorySidebar and CategorySidebar
- Refactor the findActiveAncestor etc. logic duplication into one common composition function as it'd be duplicated for the third time if this PR was merged
> feat(catalog): breadcrumbs

- packages/theme/components/ProductAddReviewForm.vue
Fixed review submission on PDP
> fix: fixed review submition on PDP

- packages/theme/composables/useCategorySearch/index.ts
- set loading to true when searching for categories is starting
- set error to null when they are results
- set results to null when there is an error
> fix: fixed useCategorySearch issues

- packages/theme/pages/Product.vue
> fix: tags resolving on pdp

- packages/theme/components/Header/SearchBar/SearchBar.vue
- packages/theme/components/Header/SearchBar/SearchResults.vue
I completely removed category results as it was broken. In general, once we will work on search functionality we should rethink it thoroughly.
- remove category results from search results
Refactor, performance
-
> refactor: search results

- docs/.vuepress/config.js
- packages/theme/composables/index.ts
- packages/theme/composables/useUiState/index.ts
- packages/theme/composables/useUiState/useUiState.ts
This PR adds documentation for the `useUiState` composable
> docs: `useUiState` composable

- docs/.vuepress/config.js
- packages/theme/composables/index.ts
- packages/theme/composables/useUiNotification/index.ts
- packages/theme/composables/useUiNotification/useUiNotification.ts
This PR adds documentation for the `useUiNotification` composable
> docs: `useUiNotification` composable

- .github/workflows/deploy-vue-storefront-cloud.yml
External checkout was enabled by mistake. We have to disable it.
> fix: disabled external checkout on production env

- packages/theme/components/MyAccount/PasswordResetForm.vue
- update button type to properly trigger form submit action
M2-499
1. Log in as a customer
2. GO to the my account page, password reset tab
3. Update your password
4. Observe that there is a proper message and password was updated successfully
> fix: password reset issue

- README.md
> docs: updated readme links

- packages/theme/components/NewProducts.vue
- packages/theme/lang/de.js
- packages/theme/lang/en.js
- packages/theme/pages/Home.vue
https://vsf.atlassian.net/browse/M2-411
> feat: home page - changed products carousel to products section

- packages/theme/pages/Home.vue
https://vsf.atlassian.net/browse/M2-412
> feat: homepage - lazy load offscreen components

- packages/theme/composables/useCart/useCart.ts
- packages/theme/composables/useReview/useReview.ts
- packages/theme/getters/types.d.ts
- packages/theme/pages/Product.vue
prevent content jump when a variant is selected on PDP
#803
> fix: prevent content jump when variant is selected on PDP

- packages/theme/jest-setup.js
- packages/theme/modules/catalog/category/components/__tests__/CategoryEmptyResults.spec.ts
Added tests for CategoryEmpty results component
https://vsf.atlassian.net/jira/software/c/projects/M2/boards/51/backlog?view=detail&selectedIssue=M2-440&issueLimit=100
yarn test:theme
> test: categoryEmptyResults component

- packages/theme/modules/catalog/pages/product.vue
- packages/theme/modules/catalog/pricing/__tests__/getConfigurableProductPriceCommand.spec.ts
- packages/theme/modules/catalog/pricing/__tests__/getGroupedProductPriceCommand.spec.ts
- packages/theme/modules/catalog/pricing/__tests__/mock/ConfigurableProductWithSelection.mock.ts
- packages/theme/modules/catalog/pricing/__tests__/mock/ConfigurableProductWithoutSelection.mock.ts
- packages/theme/modules/catalog/pricing/__tests__/mock/GroupedProduct.mock.ts
- packages/theme/modules/catalog/pricing/getConfigurableProductPriceCommand.ts
- packages/theme/modules/catalog/pricing/getGroupedProductPriceCommand.ts
- packages/theme/modules/catalog/product/components/GroupedProductSelector.vue
- packages/theme/modules/catalog/product/enums/ProductTypeUnion.ts
fix: invalid prices on grouped and configurable product
- fix issue with initial grouped product price resolving
- add configurable product price calculation
> fix: invalid prices on grouped and configurable product

- packages/theme/modules/catalog/category/composables/useFacet/input/createProductAttributeFilterInput.ts
- packages/theme/modules/catalog/pages/category.vue
- rework category filter resolving to always include root category id
M2-570
> fix: filter by category issue

- packages/theme/modules/catalog/pages/product.vue
make mobile store banner lazy-loaded on PDP
> perf: make mobile store banner lazy loaded on PDP

- packages/theme/modules/catalog/pages/product.vue
- change loading revies behavior, now will be loaded on explicit action
> perf: make read reviews loaded on request

- packages/api-client/src/helpers/magentoLink/graphQl.ts
- mute all graphql-authorization errors to avoid unwanted authorization errors in the console
> fix: remove unwanted authorization errors in the console

- packages/theme/modules/catalog/category/components/filters/renderer/CheckboxType.vue
- packages/theme/modules/catalog/category/components/filters/renderer/RadioType.vue
entities on filters are not displayed properly
> fix: entities on filters are not displayed properly

- packages/theme/modules/customer/pages/MyAccount/MyWishlist.vue
- packages/theme/modules/wishlist/composables/useWishlist/index.ts
https://vsf.atlassian.net/browse/M2-503
> fix: fixed errors during wishlist loading

- packages/theme/modules/customer/composables/useUser/index.ts
fix: wrong warning announcement on modal window to login
#963
> fix: wrong warning announcement on modal window to login

- packages/theme/lang/de.js
- packages/theme/lang/en.js
- packages/theme/modules/customer/pages/MyAccount/MyWishlist.vue
- packages/theme/modules/wishlist/components/EmptyWishlist.vue
- packages/theme/modules/wishlist/components/WishlistSidebar.vue
- packages/theme/modules/wishlist/components/__tests__/EmptyWishlist.spec.ts
https://vsf.atlassian.net/browse/M2-500
> fix: empty wishlist implementation

- packages/theme/modules/catalog/category/components/filters/FiltersSidebar/SelectedFilters.vue
fix: add html content purify for the selected filters
#974
> fix: add html content purify for the selected filters

- package.json
> build: restored composables build

- package.json
Restore `publish:composables` script
> build: restored composables publish script

- packages/theme/modules/customer/pages/MyAccount/OrderHistory/SingleOrder/OrderSummaryRow.vue
https://vsf.atlassian.net/browse/M2-508
> fix: fixed order summary styles

- docs/.vuepress/config.js
- docs/package.json
- Fixed issues with docs deployment
- removed duplicated performance section
> build: updated docs build

- packages/theme/lang/de.js
- packages/theme/lang/en.js
- packages/theme/modules/catalog/category/components/views/__tests__/CategoryProductGrid.spec.ts
- packages/theme/modules/catalog/category/components/views/__tests__/CategoryProductList.spec.ts
- packages/theme/modules/catalog/pages/product.vue
- packages/theme/modules/checkout/composables/useCart/index.ts
- packages/theme/modules/customer/pages/MyAccount/MyWishlist.vue
- packages/theme/modules/wishlist/components/WishlistSidebar.vue
- packages/theme/modules/wishlist/composables/useWishlist/index.ts
- packages/theme/modules/wishlist/composables/useWishlist/useWishlist.ts
https://vsf.atlassian.net/browse/M2-502
> feat: add product to cart from wishlist

- packages/theme/modules/catalog/category/components/filters/renderer/CheckboxType.vue
- packages/theme/modules/catalog/category/components/filters/renderer/RadioType.vue
- packages/theme/modules/catalog/category/components/filters/renderer/SwatchColorType.vue
- packages/theme/modules/catalog/category/components/filters/renderer/YesNoType.vue
- packages/theme/modules/catalog/category/components/filters/renderer/__tests__/CheckboxType.spec.ts
- packages/theme/modules/catalog/category/components/filters/renderer/__tests__/RadioType.spec.ts
- packages/theme/modules/catalog/category/components/filters/renderer/__tests__/SwatchColorType.spec.ts
- packages/theme/modules/catalog/category/components/filters/renderer/__tests__/YesNoType.spec.ts
- packages/theme/test-utils/mocks/categoryFiltersMock.ts
- packages/theme/test-utils/mocks/injectMock.ts
https://vsf.atlassian.net/browse/M2-437
> test: add tests for filter renderers

- packages/theme/modules/catalog/category/components/filters/FiltersSidebar/SelectedFilters.vue
- packages/theme/modules/catalog/category/components/filters/FiltersSidebar/__tests__/SelectedFilters.spec.ts
- packages/theme/test-utils/mocks/removableFiltersMock.ts
https://vsf.atlassian.net/browse/M2-436
> test: added tests for selectedfilters component

- packages/theme/modules/catalog/category/components/filters/CategoryFilters.vue
- packages/theme/modules/catalog/category/components/filters/__tests__/CategoryFilters.spec.ts
- packages/theme/modules/catalog/category/components/filters/renderer/__tests__/CheckboxType.spec.ts
- packages/theme/modules/catalog/category/components/filters/renderer/__tests__/RadioType.spec.ts
- packages/theme/modules/catalog/category/components/filters/renderer/__tests__/SwatchColorType.spec.ts
- packages/theme/modules/catalog/category/components/filters/renderer/__tests__/YesNoType.spec.ts
- packages/theme/test-utils/mocks/categoryFiltersMock.ts
- packages/theme/test-utils/mocks/useUiHelpersMock.ts
https://vsf.atlassian.net/browse/M2-438
> test: added tests for categoryfilters component

- .github/workflows/deploy-vue-storefront-cloud.yml
We plan some DevOps work on the Magento virtual machine so I want to temporarily change Magento backend URL so as not to block the work
> chore: temporary changed Magento instance

- packages/theme/components/SkeletonLoader/index.vue
- packages/theme/modules/catalog/pages/product.vue
- packages/theme/modules/catalog/product/components/ProductSkeleton.vue
Added product skeleton instead of the loader to fix layout shift issue on the product page.
Improving performance and UX.
tested on my local, using network throttling on various types of products.
> feat: added productSkeleton component

- .github/workflows/deploy-vue-storefront-cloud.yml
Restored Magento instance URL after the upgrade.
> chore: restored Magento instance URL

- .github/workflows/conventional-pr-name.yml
- .github/workflows/publish-npm.yml
- .github/workflows/test.yml
Updated to setup-node v3, and removed yarn cache.
> build: fixed setup-node action

- packages/theme/modules/customer/composables/useUser/index.ts
- added notifications when Magento API returns errors during registration
> refactor: added ui notifications to register form

- packages/theme/modules/checkout/components/UserShippingAddresses.vue
Fixed CSS issues related to shipping addresses in checkout.
> fix: m2-709. fixed shipping addresses layout on checkout shipping step

- packages/theme/modules/wishlist/components/WishlistSidebar.vue
Wishlist show products limit increased
#1048 
1. Login.
2. Add > 10 products to Wishlist.
3. Refresh the page.
4. Open the Wishlist.
> fix: m2-619. wishlist show products limit increased

- .github/workflows/deploy-vue-storefront-cloud.yml
- .vuestorefrontcloud/docker/nuxt.config.additional.js
- packages/theme/nuxt.config.js
- packages/theme/package.json
- yarn.lock
Fix reCaptcha config keys and enable it on production
#527
> fix: error during recaptcha verification

- packages/theme/modules/catalog/category/components/views/CategoryProductGrid.vue
- packages/theme/modules/catalog/category/components/views/CategoryProductList.vue
- remove z-index from btn to prevent overlapping
> fix: mobile category add to cart button is missin on mobile view

- .github/workflows/deploy-vue-storefront-cloud.yml
> fix: temporary disable reCaptcha

- .github/workflows/deploy-vue-storefront-cloud.yml
> fix: recaptcha

- packages/theme/lang/de.js
> fix: m2-697. category page filters translation

- packages/theme/components/BottomNavigation.vue
- fix add to cart label on the mobile menu
> fix: m2-743. incorrect add-to-cart label on mobile menu

- .github/workflows/deploy-vue-storefront-cloud.yml
- changed min score, 
- removed VSF_RECAPTCHA_HIDE_BADGE
> build: changed recaptcha config

- .github/workflows/deploy-vue-storefront-cloud.yml
- packages/theme/nuxt.config.js
Set up middleware URL based on the GitHub ref.
> build: changed middleware url building script

- yarn.lock
Reverts vuestorefront/magento2#1240
> Revert "build: updated yarn.lock"

- docs/installation-setup/configure-integration.md
- packages/theme/.env.example
- packages/theme/.gitignore
- packages/theme/middleware.config.js
- packages/theme/modules/magento/plugin.ts
- packages/theme/nuxt.config.js
- packages/theme/package.json
I have added configurable cookies options so it will be possible to customize cookies set mods.
> feat: secure cookie attribute is not set

- packages/theme/composables/useMagentoConfiguration/UseMagentoConfiguration.ts
Changed hard-coded import to import from the module.
> fix: fixed api-client import in the useMagentoConfiguration composable

- packages/theme/middleware.config.js
> fix: update cookies default settings

- packages/theme/middleware.config.js
- add crossOriginResourcePolicy
> refactor: access control header

- packages/theme/middleware.config.js
add missing http security headers
> refactor: add missing http security headers

- packages/theme/composables/useContent/useContent.ts
- packages/theme/modules/catalog/category/components/views/useProductsWithCommonCardProps.ts
- packages/theme/modules/catalog/product/components/product-types/configurable/ConfigurableProduct.vue
- packages/theme/modules/checkout/components/VsfShippingProvider.vue
- packages/theme/modules/customer/pages/MyAccount/MyReviews.vue
- packages/theme/package.json
- packages/theme/tsconfig.json
- tsconfig.json
- yarn.lock
This PR adds support for Volar, which provides better support for Vue in VS Code than Vetur.
Additionally, it fixes some of the issues reported by it.
> feat: add support for Volar

- packages/theme/components/HeroSection.vue
- packages/theme/modules/catalog/product/composables/useProductGallery/index.ts
- packages/theme/modules/catalog/product/getters/productGetters.ts
Added placeholder="blur" for hero image and products gallery
> refactor: changed default img placeholders for hero section and gallery

- packages/theme/nuxt.config.js
Reverts vuestorefront/magento2#1268
> Revert "build: changed middleware-url config"

- packages/theme/modules/checkout/pages/Checkout/Billing.vue
- packages/theme/modules/checkout/pages/Checkout/ThankYou.vue
- fixed wrong variable name on billing step
- fixed typo on thank you page
- I changed the hardcoded company name on thank you page to Vue Storefront
> fix: fixed checkout issues

- packages/theme/components/StoreSwitcher/StoresModal.vue
> fix: store modal invalid action handler name

- docs/guide/override-queries.md
> docs: fix formatting in `Override queries` guide

- yarn.lock
> feat: update yarn lock

- packages/load-tests/src/mutation/addProductsToCart.js
- packages/load-tests/src/mutation/createCustomer.js
- packages/load-tests/src/mutation/createEmptyCart.js
- packages/load-tests/src/query/storeConfig.gql.js
- packages/load-tests/src/tests/magento/addSimpleProductToCart.js
- packages/load-tests/src/tests/magento/createCustomer.js
- packages/load-tests/src/tests/magento/createEmptyGuestCart.js
- packages/load-tests/src/tests/magento/storeConfig.js
- packages/load-tests/src/tests/magento/utils/customerData.js
- packages/load-tests/src/tests/magento/utils/getHeaders.js
- packages/load-tests/src/tests/middleware/createCustomer.js
- packages/load-tests/src/tests/middleware/createEmptyGuestCart.js
- packages/load-tests/src/tests/middleware/storeConfig.js
- packages/load-tests/src/tests/middleware/utils/customerData.js
- packages/load-tests/src/tests/middleware/utils/getHeaders.js
- packages/load-tests/src/utils/getCookies.js
- yarn.lock
- add magento store config load test
- add create empty guest cart load test
- add magento create customer
> feat: load tests

- .eslintignore
- packages/load-tests/src/tests/scenarios/browsingProduct.js
- packages/load-tests/src/tests/scenarios/searchProduct.js
- packages/load-tests/src/tests/scenarios/utils/setDefaultCookies.js
> test: add search product load tests

- packages/load-tests/src/tests/scenarios/newUserRegistration.js
test: add load test for a new user registration
> test: add load test for a new user registration

- docs/installation-setup/installation.md
- change npm -> yarn because npm does not work for our app
Improvement
> fix: update installation guide

- .all-contributorsrc
- README.md
Added new contributors to the readme.md:
- @bensinca
- @sequensucks
- @drew-webscale
- @konarshankar07
- @maaarghk
> chore: added new contributors

- packages/api-client/src/api/addProductToWishList/addProductsToWishlist.ts
- packages/api-client/src/api/productDetail/productDetailsQuery.ts
- packages/api-client/src/api/products/productsList.ts
- packages/api-client/src/api/removeProductsFromWishlist/removeProductsFromWishlist.ts
- packages/api-client/src/api/wishlist/wishlist.ts
- packages/theme/modules/catalog/category/composables/useFacet/getFacetData.gql.ts
- packages/theme/modules/checkout/composables/useCart/commands/addItemCommand.ts
Add a case for GroupedProduct into addItemCommand in the useCart composable
re #718
> feat: implement add a grouped product to cart

- packages/theme/modules/catalog/product/components/ProductAddReviewForm.vue
- packages/theme/modules/catalog/product/components/RelatedProducts.vue
- packages/theme/modules/catalog/product/components/UpsellProducts.vue
- packages/theme/modules/catalog/product/components/product-types/configurable/ConfigurableProduct.vue
- packages/theme/modules/catalog/product/components/tabs/ProductTabs.vue
Replace a route query id with a route data sku after implementing #181
fix #1329
> fix!: fix product detail components

- packages/theme/modules/catalog/category/composables/useCategory/index.ts
- packages/theme/modules/core/integrationPlugin/_proxyUtils.ts
fix: pods have warnings error after deployment
- change invalid axios response
> fix: pods has warnings error after deployment

- packages/theme/nuxt.config.js
- fix server configuration issue for the ssl setup
#1299
> fix: vsf2 not working with docker compose

- .github/workflows/deploy-vue-storefront-cloud.yml
- packages/theme/nuxt.config.js
- packages/theme/package.json
- yarn.lock
- add http-cache module
- update stage middleware url env value
Provide GC CDN support for the integration
> feat: add GC CDN support

- .vuestorefrontcloud/docker/.dockerignore
- .vuestorefrontcloud/docker/Dockerfile
- yarn.lock
- improve the docker image building process
> build: improve image building process

- .github/workflows/public_env_info/canary
add missing canary url prtocols
> fix: add missing canary url protocols

- .vuestorefrontcloud/docker/Dockerfile
Improve image build time and reduce image size.
> chore: improve image build

- .vuestorefrontcloud/docker/nuxt.config.additional.js
> chore: fix base nuxt config async resolving

- .github/CODEOWNERS
- .github/workflows/docs-deployment.yaml
Update repository setup
Update codeowners and docs deployment action
IN-299
Change because of:
- changing the mainterners
- changing the way of deploying the documentation
> chore: update repo setup

- .github/workflows/deployment-template.yml
> chore: remove poll for farmer

- packages/theme/modules/checkout/pages/Checkout/Payment.vue
- remove duplicated margins in styles
> fix: checkout/pages/Checkout/payment.vue

- docs/guide/override-queries.md
> chore: fix mistake in docs->guide->queriesOverride

- docs/index.md
Added warnings to each environment to make it easier to identify and understand those.
> chore(docs): added warnings in the envs

- .github/workflows/deploy-vue-storefront-cloud.yml
- .github/workflows/docs-deployment.yaml
- .github/workflows/draft-release-pr.yml
- .github/workflows/speedcurve.yml
It fixes the usage of the deprecated --set-output command. Now, we are using a modern up-to-date approach.
[IN-1640](https://vsf.atlassian.net/jira/software/c/projects/IN/boards/108?modal=detail&selectedIssue=IN-1640&assignee=5fcf86faa1d3f100684db878)
> fix: deprecated set output

- docs/composition/composables.md
- docs/composition/list-of-composables.md
- docs/modules/catalog/filters.md
- docs/modules/catalog/product-types.md
Recently, the API Reference was removed for everything except the API Client. 
This lead to a lot of links leading to 404s, this PR changes those links to link directly to the Github source code for the interface.
> docs: fix interface source code to github

- docs/composition/useAddresses.md
- docs/composition/useApi.md
- docs/composition/useBilling.md
- docs/composition/useCart.md
- docs/composition/useCategory.md
- docs/composition/useCategorySearch.md
- docs/composition/useConfig.md
added docs:
- useAddresses
- useApi
- useBilling
- useCart
- useCategory
- useCategorySearch
Documentation
> docs(composables): added documentation for composables

- docs/composition/use-cart.md
- docs/composition/use-config.md
- docs/composition/use-content.md
> docs: fixed typos

- .github/workflows/test.yml
Add sonar cloud tests coverage
> chore: add sonarcloud tests coverage

- docs/index.md
Aligned with @WojtekTheWebDev and @Mateuszpietrusinski
> docs: update demo URL

- .github/workflows/continuous-integration.yml
Use main branch of Integration Continuous Integration workflow action
> ci: update ci workflow action

- .changeset/seven-emus-marry.md
- .github/workflows/continuous-integration.yml
- package.json
- packages/api-client/package.json
- packages/sdk/package.json
- yarn.lock
closing [https://vsf.atlassian.net/browse/IN-3406](https://vsf.atlassian.net/browse/IN-3406)
> feat: add node 18 support

- .changeset/brave-badgers-return.md
- packages/api-client/src/helpers/magentoLink/graphQl.ts
closing [https://vsf.atlassian.net/browse/IN-3553](https://vsf.atlassian.net/browse/IN-3553)
> fix: disable query deduplication

- .changeset/slow-dolls-remain.md
- packages/api-types/src/Api.ts
> fix: invalid product details name

- docs/.vuepress/config.js
- docs/getting-started/supported-features.md
[](https://vsf.atlassian.net/browse/IN-3566)
Adding list of supported features to docs
> IN-3566 docs: adding supported features

- .changeset/sweet-melons-peel.md
- packages/api-client/src/index.server.ts
- packages/sdk/src/index.ts
> feat: add domain based module compatibility

- packages/api-client/src/api/generateCustomerToken/index.ts
Fixes this: https://github.com/vuestorefront/magento2/pull/1469
Updated the generateCustomerToken API endpoint so that the mutation uses the custom query.
> fix: add the custom query to mutation (#1469)

- .changeset/tall-emus-try.md
> chore: add changelog

- .changeset/ninety-steaks-joke.md
- packages/api-types/src/Api.ts
> feat(UST-1217): UDM enhancements 5

- .changeset/calm-berries-do.md
- .changeset/fifty-carpets-play.md
- .changeset/gold-elephants-rescue.md
- packages/api-client/src/api/categories/categories.ts
- packages/api-client/src/api/categories/index.ts
- packages/api-client/src/api/categoryList/index.ts
- packages/api-client/src/api/index.ts
- packages/api-types/src/Api.ts
- packages/sdk/__tests__/integration/__config__/customQueries/categories/index.ts
- packages/sdk/__tests__/integration/__config__/customQueries/jest.customQueries.ts
- packages/sdk/__tests__/integration/__nock-fixtures__/[SDK][Integration-Tests]-categories-should-return-customized-categories-result-using-custom-query
- packages/sdk/__tests__/integration/__nock-fixtures__/[SDK][Integration-Tests]-categories-should-return-filtered-list-of-categories
- packages/sdk/__tests__/integration/__nock-fixtures__/[SDK][Integration-Tests]-categories-should-return-list-of-all-categories
- packages/sdk/__tests__/integration/categories.integration.spec.ts
- packages/sdk/src/methods/categories/index.ts
- packages/sdk/src/methods/index.ts
closing https://alokai.atlassian.net/browse/ES-250
> feat: add categories method

- .changeset/popular-bats-suffer.md
> chore: add missing changeset

- .changeset/cyan-monkeys-drive.md
- .changeset/gentle-islands-ring.md
- .github/workflows/continuous-integration.yml
- packages/api-client/package.json
- packages/sdk/package.json
- yarn.lock
No issue
---
"@vue-storefront/magento-api": patch
---
[CHANGED] Updated `@vue-storefront/middleware` version to `4.x.x`.
---
"@vue-storefront/magento-sdk": patch
---
[CHANGED] Updated `@vue-storefront/middleware` peer dependency version to `4.x.x`.
> chore: middleware v4 update

- docs/content/1.index.md
- docs/content/2.getting-started/1.quick-start.md
Changes about Open Source model in the docs
> chore: docs

- docs/content/1.index.md
- docs/content/2.getting-started/1.quick-start.md
> chore: Os changes
