vuestorefront/magento2

- .github/workflows/publish.yml
- package.json
- packages/api-client/package.json
- packages/composables/package.json
- scripts/.npmrc
- scripts/lib/publishPackages.js
- yarn.lock
chore: release 1.0.0-beta.9
- `api-client`
- Removed non-default fields on GraphQL queries
- `general`
- Some issues related to release CICD process
- Composeable and theme imports of new methods
- `theme`
- Removed unused nuxt route
> chore: changed publish script to node exec

- packages/theme/package.json
- yarn.lock
- Just simple fix for storefront-ui version in package.json
- Skips version 0.10.71
- Does not require updates in feature, but could be done if guys from storefront-ui will fix the issue like suggested: https://github.com/vuestorefront/storefront-ui/issues/1952#issuecomment-898865188
https://github.com/vuestorefront/magento2/issues/138
> fix(theme): update storefront-ui dependency

- packages/api-client/src/api/setShippingMethodsOnCart/setShippingMethodsOnCart.ts
- packages/composables/src/composables/useShippingProvider/index.ts
Shipping data is loaded from cart, so in order to display it right we load cart from M2 in setShippingMethodsOnCart same as done for other cart modifications, like removeItemFromCart, etc. 
https://github.com/vuestorefront/magento2/issues/144
1. Proceed to checkout and select shipping method
2. Check shipping provider and other cart data
> fix: add shipping provider to basket

- packages/composables/src/composables/useCart/index.ts
If customer was logged in and useBasket.load was executed, no cart_id was stored to apiState which caused infinite loop on add to basket. Fixed. 
https://github.com/vuestorefront/magento2/issues/166
> fix: set cart id for logged in customer

- packages/theme/components/Checkout/VsfShippingProvider.vue
Remove duplicated api call
When user choose the shipping adress, the shipping method api was called, but following the api magento guide, the shipping method should be called after user choose the billing address.
I changed the method that was called when user choose the shipping address to not call shipping method api yeat, it will just set the value of choosed shipping method and after choose the billing address the shipping method will be called.
The 'save' API was called twice during the Checkout process. At this step, it should only store the data using setState, not call the API.
To reproduce the problem, add an item to a cart.
When you are doing the checkout process, pay attention at network tab on devtools, and notice that when you choose your shipping address the shipping method …
> fix(theme): remove duplicated api call

- packages/theme/components/CartSidebar.vue
Updated <SfCollectedProduct> v-for :key to remove 'math.random' as this was regenerating unique keys and causing the cart item to re-render when updating quantity. Magento product SKUs are unique so all items will have a unique key without this.
https://github.com/vuestorefront/magento2/issues/287
Improve user experience to stop content in the cart sidebar from jumping around
Change tested on a new install of the latest VSF version, with clean Magento install using sample data
> fix(theme): update cart item key to stop rendering

- docs/.vuepress/config.js
- docs/guide/roadmap.md
> docs: added roadmap to the docs

- packages/theme/pages/Category.vue
Fix for #384 
#384 
Bugfix
Once filter is set, reload page and observe if sort order is populated
> fix(theme): fix preselection of sort order when query param is available

- packages/composables/src/composables/useBilling/index.ts
- packages/composables/src/composables/useShipping/index.ts
- packages/theme/pages/Checkout/UserAccount.vue
- packages/theme/pages/Checkout/__tests__/UserAccount.spec.js
Fixed when a user wants to place an order as a guest.
Fix for #247 
The problem was that the guest email address was not set correctly. 
Also fixed when passing the "neighborhood" and "extra" param when setting the billing address and shipping address.
If the params are empty, they are filtered out
Updated tests
Now a guest can place an order
> fix: broken cart after placing order as guest

- packages/theme/pages/Category.vue
> fix(theme): fix flashing category page

- packages/composables/src/getters/userAddressesGetters.ts
- packages/theme/components/UserAddressDetails.vue
- packages/theme/lang/en.js
Fix the missing text "default billing address"
Add information about default billing address next to the information about default shipping in address row
Reorganize the view and stand default shipping and default billing address above other addresses.
> fix: default billing information does not appear on address

- .gitignore
- packages/theme/components/AppHeader.vue
- packages/theme/components/BottomNavigation.vue
- packages/theme/components/CartSidebar.vue
- packages/theme/helpers/cart/addToCart.ts
- packages/theme/pages/Checkout.vue
- packages/theme/pages/Checkout/Billing.vue
- packages/theme/pages/Checkout/Payment.vue
- packages/theme/pages/Checkout/Shipping.vue
- packages/theme/pages/Checkout/UserAccount.vue
- packages/theme/pages/MyAccount.vue
- packages/theme/pages/MyAccount/AddressesDetails.vue
- packages/theme/pages/MyAccount/MyWishlist.vue
- packages/theme/pages/MyAccount/OrderHistory.vue
- packages/theme/pages/Product.vue
- packages/theme/pages/Shipping.vue
- packages/theme/test-utils.js
Localization routes push and nuxt-links.
-
Bugfix
Go through
> fix(theme): fix links to catch current locale

- packages/theme/components/TopBar.vue
- packages/theme/nuxt.config.js
Enable the currency switcher on the `TopBar.vue` component, and add the configuration to prevent the cookie from auto changing.
closes #355  
This feature has been tested locally, and previously tested.
> refactor(theme): enable the currency switcher on `TopBar.vue`

- packages/theme/pages/Category.vue
Fix disappearing category sidebar on category page when category or filters were changed
#285 
Bugfix
> fix(theme): fix disappearing category sidebar filter change

- packages/api-client/src/index.server.ts
- packages/composables/src/composables/useCart/index.ts
- packages/composables/src/getters/cartGetters.ts
- packages/theme/components/CartSidebar.vue
- packages/theme/components/SearchResults.vue
- packages/theme/components/__tests__/CartSidebar.spec.js
- packages/theme/enums/stockStatusEnum.js
- packages/theme/lang/en.js
- packages/theme/layouts/default.vue
- packages/theme/test-utils.js
- packages/theme/test-utils/mocks/cartGetters.js
- packages/theme/test-utils/mocks/index.js
- packages/theme/test-utils/mocks/useCart.js
- packages/theme/test-utils/mocks/useUiState.js
- fix empty cart issue when one or more products were out of stock
- move cart loading from layout to CartSidebar component for a non-blocking cart data load
- add Out Of Stock flag on a product in minicart
- change apollo client query strategy None -> All so the frontend/composables are now able to process eventual errors.
#235
With the usage of the test product, toggle its stock status and observe behavior on the frontend.
Sample scenarios:
Test#1
- add a product to the cart
- go to Magento Admin Panel and flag that product as OOS.
- on the VSF, reload page
- observe that label is visible on the product, quantity action input is hidden, the cart was loaded properly
> fix(theme): out of stock product will no longer break cart

- packages/theme/components/TopBar.vue
- packages/theme/nuxt.config.js
Reverts vuestorefront/magento2#421 because it causes unexpected errors: 
```
Mateuszs-MacBook-Pro:~ mkoszutowski$ kubectl -n demo-magento2-canary-europe-west1-gcp-storefrontcloud-io logs vue-storefront-dc9fb84bd-wmgkz
yarn run v1.22.15
$ cd packages/theme && yarn start
$ nuxt start
WARN  [Magento: Middleware Config] Not found any configuration file, will use the ENV variable or default configuration.
ℹ Middleware starting....
ℹ Loading integrations...
ℹ - Loading: magento @vue-storefront/magento-api/server
ℹ - Loading: magento extension: tokenExtension
✔ - Integration: magento loaded!
✔ Integrations loaded!
✔ Middleware created!
ℹ Modern bundles are detected. Modern mode (server) is enabled now.
ℹ Listening on: http://10.3.21.199:3000/
ERROR  Currency code is required with currency style. …
```
> fix: revert "refactor(theme): enable the currency switcher on `TopBar.vue`"

- packages/theme/nuxt.config.js
Updated the nuxt.config.js by increasing the enforceSizeThreshold and removing configuration properties
The rebuild should be faster during development.
Performance increased with ~40 - 45 procent
The full rebuild took: **1130.13 ms**
The full rebuild took: **573.09 ms**
> perf: updated js chunks configuration

- packages/api-client/src/api/cart/cart.ts
- packages/composables/src/getters/cartGetters.ts
- packages/theme/components/CartSidebar.vue
For configurable products, some data were pulled from a parent which yield issues with the duplicated key in the list or the wrong image.
#434 
#435 
Bugfixing and improvement
1. Add a few variants of a configurable product to the cart
2. Observe that all variants have proper images
3. Check console if there is any duplicate key error
> fix(minicart): fix resolving configurable variants data

- packages/composables/src/composables/useUser/index.ts
- packages/theme/components/MyAccount/PasswordResetForm.vue
- packages/theme/pages/MyAccount/MyProfile.vue
Previously error and success messages were not displayed and the change password action always
lead to an error, now either update data and password change are handled properly
- update packages/theme/pages/MyAccount/MyProfile.vue component to properly handle user data update actions.
-
bugfix
1. Log in as a customer
2. Go to your account details tab
3. Try to update your data or to change password (with a valid and invalid data)
4. Observe relevant messages and action outcome
5. Also try to change the password with an invalid current password input and observe the behavior
> fix(theme): fix customer account update data and password change functionality

- packages/theme/components/BottomNavigation.vue
#293
Tested using Chrome on Mac, responsive view, and Sizzy to simulate other resolutions/device densities. 
There is a followup issue to this which is that safe-area-inset is not handled for iOS 10+, so the menu ends up being overlapped by the bottom "chin" on iOS.
> fix(theme): fix mobile home button alignment

- packages/theme/layouts/default.vue
Small update for a footer lazy-loading
-
-
-
> fix(theme): fix footer lazy hydration

- packages/theme/pages/Page.vue
Fixed loading content for CMS pages.
There was a bug during load cms data from magento:
```
ERROR  [VSF][error]:  [GraphQL error]: Message: "Page id/identifier should be specified, Location: [column: 3, line: 2], Path: cmsPage  
```
#494 
CMS pages and a Page route should work as excepted.
Tested on my local env manually.
> fix(theme): fixed cms page loading

- packages/theme/components/WishlistSidebar.vue
- packages/theme/layouts/default.vue
Further improvement and fixes for lazyloading in the default layout. Additionally I fixed wishlist loading.
Improvement
-
> fix(theme): ssr optimization for default layout

- packages/theme/pages/MyAccount/OrderHistory.vue
Removed the download option and made details button available on mobile.
#301
> fix(theme): orders history table - no order details button on mobile

- packages/theme/composables/useMagentoConfiguration.ts
- packages/theme/plugins/__tests__/i18n.spec.js
- packages/theme/plugins/i18n.ts
Fix setting up locale and store configuration in case there is no cookie set yet.
-
bugfix
- delete all cookies
- reload page and observe if app is bootstrapped with proper store
- eg. for <domain>/german everything must be translated and localised
- also check vsf-* cookies configuration
- you must always land in requested store (eg. if want to use /german I mustn't go to default)
> fix(theme): fix setting proper store and locale if there is no cookie

- .vuestorefrontcloud/docker/Dockerfile
Added vsf registry to the deployment build.
> chore: updated dockerfile

- packages/theme/components/HTMLContent.vue
- packages/theme/package.json
- yarn.lock
- add lodash.unescape to handle escaped HTML from Magento
#514 
- bugfix
Visit pages:
- cms page
- product page
- any page with content from Magento 2
- to double-check, resave product with updated description to make an "escaped save" on the Magento side, then check that product in VSF
> fix(theme): add html unescaping in HTMLContent component

- packages/theme/pages/Category.vue
fix add to wishlist button on category listing view for mobile devices
#545 
bugfix
- Go to a category page on mobile device/view
- Switch view from grid to list
- Click "save for later" to add/remove the product from wishlist
> fix(theme): fix add to wishlist button on category listing view for mobile devices

- packages/theme/components/MyAccount/AddressForm.vue
- packages/theme/pages/MyAccount/AddressesDetails.vue
save or update of address details in the customer account will no longer yield 404
#548 
-
1. Open home page on mobile device/view
2. Log in/Register as a customer
3. Navigate to My Account panel
4. Navigate to Adress Details subpage
5. Click "Add new address"
6. Fill the form and submit
-
> fix(theme): fix invalid customer address save action route push

- packages/theme/components/AppFooter.vue
- packages/theme/components/HTMLContent.vue
- packages/theme/nuxt.config.js
- packages/theme/package.json
- packages/theme/pages/Checkout/ThankYou.vue
- packages/theme/plugins/dompurify.ts
- yarn.lock
- remove core @vue-storefront/magento-theme module to save build weigh, module was no more necessary
but had an impact on the final build
- rework dompurify as a plugin to save bundle size
BREAKING CHANGE: - remove core @vue-storefront/magento-theme dependency
-
performance improvement
-
> refactor(theme): remove core _theme module

- packages/composables/src/composables/useConfig/index.ts
- packages/composables/src/composables/useExternalCheckout/index.ts
- packages/composables/src/factories/useConfigFactory.ts
- packages/composables/src/getters/storeConfigGetters.ts
- packages/theme/components/StoreSwitcher.vue
- packages/theme/composables/index.ts
- packages/theme/composables/useConfig/index.ts
- packages/theme/composables/useConfig/useConfig.d.ts
- packages/theme/composables/useMagentoConfiguration.ts
- packages/theme/plugins/dompurify.ts
- packages/theme/stores/config.ts
- mark composable useConfig as deprecated
- move composable to theme module
- rework composable to get rid of core dependency and to utilize Pinia store
> refactor(theme): refactor useConfig composable

- packages/composables/src/composables/useStore/index.ts
- packages/composables/src/factories/useStoreFactory.ts
- packages/theme/components/StoreSwitcher.vue
- packages/theme/composables/index.ts
- packages/theme/composables/useConfig/index.ts
- packages/theme/composables/useStore/index.ts
- packages/theme/composables/useStore/useStore.d.ts
- packages/theme/stores/config.ts
refactor(theme): refactor useStore composable
- mark useStore as deprecated in composables
- add useStore composable in a theme module
BREAKING CHANGE: rework useStore composable
-
-
-
> refactor: m2-154. refactor use store composable to use pinia store

- packages/composables/src/composables/useFacet/index.ts
- packages/theme/components/AppHeader.vue
- packages/theme/composables/index.ts
- packages/theme/composables/useFacet/_utils.ts
- packages/theme/composables/useFacet/index.ts
- packages/theme/composables/useFacet/useFacet.d.ts
- packages/theme/pages/Category.vue
- refactored useFacet composable
> refactor: refactored useFacet composable

- packages/api-client/src/api/cartTotalQty/cartTotalQty.ts
- packages/api-client/src/api/cartTotalQty/index.ts
- packages/api-client/src/api/index.ts
- packages/api-client/src/types/API.ts
- packages/composables/src/composables/useCart/index.ts
- packages/composables/src/factories/useCartFactory.ts
- packages/theme/components/AppHeader.vue
- packages/theme/components/CartSidebar.vue
- packages/theme/layouts/default.vue
- packages/theme/test-utils/mocks/useCart.js
- add loadTotalQuantity method on the cart composable as sometimes this is the only information needed
- add lazy load for a mini cart
- header will pull only total quantity data instead of loading the whole cart
-
Check cart items qty displayed in the header for many scenarios for guest, customer, cart merging etc.
> refactor(general): refactor how and where the cart is loaded

- packages/composables/src/composables/useCart/index.ts
- packages/composables/src/composables/useConfig/index.ts
- packages/composables/src/composables/useCustomQuery/index.ts
- packages/composables/src/factories/useCustomQueryFactory.ts
- packages/theme/components/CurrencySelector.vue
- packages/theme/components/CurrencySelector/CurrenciesModal.vue
- packages/theme/components/StoreSwitcher.vue
- packages/theme/components/StoreSwitcher/StoresModal.vue
- packages/theme/components/TopBar/checkStoresAndCurrency.gql.ts
- packages/theme/components/TopBar/index.vue
- packages/theme/components/TopBar/useTopBar.ts
- packages/theme/composables/useApi/index.ts
- packages/theme/composables/useMagentoConfiguration.ts
- packages/theme/layouts/default.vue
- packages/theme/middleware.config.js
- packages/theme/nuxt.config.js
- packages/theme/package.json
- yarn.lock
💅 Refactors
`composables`
- fixed type error in the `useCart` composables that appeared when cart was empty
- added debug log in the `useConfig` loadConfig method in the `useConfig` composable
- made the `useCustomQuery` composable depraacated
`theme`
- refactored the `useMagentoContiguration` composables to load only config
- added StoresModal component and moved loading stores there
- added CurrenciesModal component and moved loading currencies there
- make those components lazy-loaded
- refactored styles of the `CurrencySelector` and  the `StoreSwitcher` components
- refactored the `TobBar` component, moved all business logic to the `useTopBar` composable
🚀 Features
`theme`
- added the `useApi` composable (which replaces the `useCustomQuery` composable) and the possibility to run …
> refactor: introduced the useApi composable, refactored loading configuration

- packages/api-client/src/api/index.ts
- packages/api-client/src/api/wishlistItemsCount/index.ts
- packages/api-client/src/api/wishlistItemsCount/wishlistItemsCount.ts
- packages/api-client/src/types/API.ts
- packages/composables/src/composables/useCart/index.ts
- packages/composables/src/composables/useUser/index.ts
- packages/composables/src/composables/useWishlist/index.ts
- packages/composables/src/factories/useCartFactory.ts
- packages/composables/src/factories/useWishlistFactory.ts
- packages/composables/src/getters/wishlistGetters.ts
- packages/composables/src/types/composables.ts
- packages/theme/components/AppHeader.vue
- packages/theme/components/CartSidebar.vue
- packages/theme/components/LoginModal.vue
- packages/theme/components/WishlistSidebar.vue
- packages/theme/components/__tests__/LoginModal.spec.js
- packages/theme/layouts/default.vue
- packages/theme/pages/MyAccount.vue
- packages/theme/test-utils/mocks/useCart.js
-
Performance improvement
- Check if the wishlist total count is loaded properly and displayed in the header when customers log in
- Check if wishlist is properly removed when customer log out
- Check if wishlist and its counter are properly updated when user add/remove item from wishlist
> feat(theme): add wishlist lazyload and totalItems shared field

- packages/composables/src/composables/useCart/index.ts
- packages/theme/pages/Category.vue
add sorting select in the navbar on the mobile category view
-
-
-
> feat(theme): add sorting select in the navbar on the mobile category view

- packages/theme/components/TopBar/useTopBar.ts
- made TopBar lazy-loaded
- remove async/await in useTopBar to unblock main thread working
> refactor(theme): made top bar graphql requests non-blocking

- packages/theme/components/Header/SearchBar/SearchBar.vue
- packages/theme/utilities/directives/click-outside/click-outside-directive.js
Fix for: #625 
There is a directive active "click-outside" of an element. This was available on only the search-input field. So when you click on something else than the input-field, the search results are removed before the routing can take place.
This issue is fixed now.
> fix: search customer is not being moved to product details page

- packages/theme/pages/Home.vue
- changed useFetch to useAsync in the homepage to display new products carousel
[#M2-325](https://vsf.atlassian.net/browse/M2-325)
#731 
bugfixing
tested on local env in production mode
> fix(homepage): fixed new products carousel ssr rendering issues

- packages/composables/src/getters/_utils.ts
- packages/composables/src/getters/addressGetter.ts
- packages/composables/src/getters/cartGetters.ts
- packages/composables/src/getters/categoryGetters.ts
- packages/composables/src/getters/checkoutGetters.ts
- packages/composables/src/getters/facetGetters.ts
- packages/composables/src/getters/forgotPasswordGetters.ts
- packages/composables/src/getters/index.ts
- packages/composables/src/getters/orderGetters.ts
- packages/composables/src/getters/productGetters.ts
- packages/composables/src/getters/reviewGetters.ts
- packages/composables/src/getters/storeConfigGetters.ts
- packages/composables/src/getters/storeGetters.ts
- packages/composables/src/getters/userAddressesGetters.ts
- packages/composables/src/getters/userBillingGetters.ts
- packages/composables/src/getters/userGetters.ts
- packages/composables/src/getters/userShippingGetters.ts
- packages/composables/src/getters/wishlistGetters.ts
- packages/composables/src/index.ts
- packages/theme/pages/Home.vue
We must keep getters in legacy code as long as legacy code is a part of the application
- copy getters back to the legacy composables for a backward compatibility package and mark all as deprecated
> fix(composables): revert getters

- packages/api-client/package.json
- packages/api-client/src/helpers/magentoLink/graphQl.ts
- yarn.lock
Resolve https://github.com/vuestorefront/magento2/issues/735
I found that every call made by VSF was slower than an API Client like Postman for example. After a few research i found that we are losing time to make a connection ( HTTPS round trip and so on... ).
- Home/Product/Categories/MyAccount pages have been tested.
- Add to cart, remove, update.
- Login/Logout
:warning: this is on my local Machine, on production we can expect 10 to 30% improvement i think.
> feat(api-client): improve performance of node HTTP calls

- packages/composables/src/composables/usePaymentProvider/index.ts
- packages/composables/src/factories/usePaymentProviderFactory.ts
- packages/theme/components/Checkout/VsfPaymentProvider.vue
- packages/theme/composables/index.ts
- packages/theme/composables/usePaymentProvider/commands/getAvailablePaymentMethodsCommand.ts
- packages/theme/composables/usePaymentProvider/commands/setPaymentMethodOnCartCommand.ts
- packages/theme/composables/usePaymentProvider/index.ts
- packages/theme/composables/usePaymentProvider/usePaymentProvider.d.ts
Refactor use payment provider, move it to the Theme package, mark composable as deprecated
-
-
-
> refactor(composables):  use payment provider

- packages/theme/pages/Checkout/Billing.vue
- selecting billing address will now unlock move to next step action
-
bugfix after refactoring of composables
1. add the product to the cart
2. fill user data form and go to the shipping step
3. fill in shipping address
4. select shipping method
5. go to the billing step
6. fill in billing address or select “My billing and shipping address are the same”
> fix(checkout): fix issue with blocked payment method step

- packages/composables/src/composables/useAddresses/index.ts
- packages/composables/src/composables/useCategory/index.ts
- packages/composables/src/composables/useCategorySearch/index.ts
- packages/composables/src/composables/useCustomMutation/index.ts
- packages/composables/src/composables/useCustomQuery/index.ts
- packages/composables/src/composables/useExternalCheckout/index.ts
- packages/composables/src/composables/useForgotPassword/index.ts
- packages/composables/src/composables/useGetShippingMethods/index.ts
- packages/composables/src/composables/useNewsletter/index.ts
- packages/composables/src/composables/useRelatedProducts/index.ts
- packages/composables/src/composables/useReview/index.ts
- packages/composables/src/composables/useUpsellProducts/index.ts
- packages/composables/src/composables/useUser/index.ts
- packages/composables/src/composables/useUserOrder/index.ts
- packages/composables/src/composables/useWishlist/index.ts
- packages/composables/src/factories/useAddressesFactory.ts
- packages/composables/src/factories/useCategorySearchFactory.ts
- packages/composables/src/factories/useCustomQueryFactory.ts
- packages/composables/src/factories/useExternalCheckoutFactory.ts
- packages/composables/src/factories/useForgotPasswordFactory.ts
- packages/composables/src/factories/useGetShippingMethodsFactory.ts
- packages/composables/src/factories/useMutationQueryFactory.ts
- packages/composables/src/factories/useRelatedProductsFactory.ts
- packages/composables/src/factories/useUpsellProductsFactory.ts
- packages/composables/src/factories/useWishlistFactory.ts
- packages/composables/src/helpers/buildCategoryTree.ts
- packages/composables/src/helpers/compareWishlist.ts
- packages/composables/src/helpers/findItemOnWishlist.ts
- packages/composables/src/helpers/htmlDecoder.ts
- packages/composables/src/helpers/userAddressManipulator.ts
> refactor(composable): add missing depercated annotations

- packages/theme/composables/useUiNotification/index.ts
Once the message is displayed, the cookie with a message will be removed to avoid displaying the message endlessly.
-
bugfix
1. log in as a customer
2. remove cookie with the token
3. reload page
4. observe the message in bottom left corner
5. reload page
6. observe that the message is not there anymore
> fix(notification): remove notification cookie once the message is displayed

- packages/theme/components/MyAccount/ProfileUpdateForm.vue
- packages/theme/composables/useUser/index.ts
- packages/theme/pages/MyAccount/MyProfile.vue
- update useUser composable to assign error values for an email update action
- remove redundant form handling requests to avoid duplicated/multiplicated requests
#676 
bugfix
1. Log in/Register as a customer
2. Go to My Account
3. Navigate to My profile > Personal data
4. Change email value
5. Click "UPDATE PERSONAL DATA"
6. Insert invalid password and submit form
7. Observe relevant and proper error message in the notification modal
> fix(myaccount): fix error handling for customer data and email update action

- packages/theme/pages/MyAccount/OrderHistory.vue
Products are not connected with an order, and it's hard to establish if we can link to the product, so we decided to remove links to products from order details. 
The main problem was with configurable products and the wrong SKU on the product in orders data. There was an SKU of a child, but we need the SKU of the main product. 
#768
bugfixing
Tested on my local on order details page
> refactor: removed links from order's product

- docs/guide/configuration.md
- packages/theme/components/Header/SearchBar/SearchResults.vue
- packages/theme/components/HeaderLogo.vue
- packages/theme/components/InstagramFeed.vue
- packages/theme/components/MobileStoreBanner.vue
- packages/theme/components/Products/GroupedProductSelector.vue
- packages/theme/components/ProductsCarousel.vue
- packages/theme/components/StoreSwitcher.vue
- packages/theme/components/StoreSwitcher/StoresModal.vue
- packages/theme/components/WishlistSidebar.vue
- packages/theme/getters/productGetters.ts
- packages/theme/modules/catalog/pages/default.vue
- packages/theme/package.json
- packages/theme/pages/Checkout/Payment.vue
- packages/theme/pages/MyAccount.vue
- packages/theme/pages/MyAccount/MyWishlist.vue
- packages/theme/pages/Product.vue
- yarn.lock
- Updated `theme` components to use StorefrontUI v0.13.x
locally tested and jest
> refactor(theme): updated StorefrontUI to 0.13.0

- packages/theme/modules/catalog/category/components/navbar/CategoryNavbar.vue
- because we have a default sorting value, the additional placeholder is not required
#774 
Improvement
-
> fix(theme): remove placeholder for a sorting mechanism in the category navbar

- packages/theme/components/Checkout/UserBillingAddresses.vue
- packages/theme/pages/Checkout/Billing.vue
- add billing address persistence by loading once the step is mounted
- add selection of default address if none is selected
#773 
bugfix
1. Add product to cart and proceed to checkout
2. On ‘Billing’ step add new billing address
3. Proceed to ‘Payment’ step
4. Go back from ‘Payment’ step to ‘Billing’ step
> fix(theme): billing address is cleared while returning to billing step on checkout M2-333

- packages/theme/components/Products/BundleProductSelector.vue
- packages/theme/components/Products/GroupedProductSelector.vue
- packages/theme/pages/Product.vue
- fixed bundle products issues
- fixed gruped products issue
There was a problem with getting product data in bundle and grouped product selector components. Bundle/grouped options weren't visible. 
#773 769
bugfixing
Tested bundle product: Set of Sprite Yoga Straps
Tested grouped product: Set of Sprite Yoga Straps
> refactor(theme): refactored bundle and grouped products

- packages/api-client/.lintstagedrc
- packages/composables/.lintstagedrc
- packages/theme/.lintstagedrc
M2-345
I assume that under the hood lintstaged rc runs eslint three times for each file extension group instead of just once for all files. This slows things down a bit. I don't think there's much benefit of separating js ts and vue files into groups. I checked and the PR makes things a little faster
> chore: run eslint only 1 time instead of 3 times

- packages/theme/components/MobileStoreBanner.vue
- packages/theme/components/RelatedProducts.vue
- packages/theme/components/UpsellProducts.vue
- packages/theme/composables/useApi/index.ts
- packages/theme/modules/catalog/pages/default.vue
- packages/theme/modules/catalog/pricing/__tests__/usePrice.spec.js
- packages/theme/modules/catalog/pricing/getPricesQuery.gql.ts
- packages/theme/modules/catalog/pricing/usePrice.ts
- packages/theme/pages/Home.vue
- refactor(prices): make prices non-cachable
- add usePrice composable in catalog module
- rework the category page to load prices onMounted lifecycle to avoid caching
- refactor(home): make new product carousel non cachable
- load products data onMounted to avoid price caching
- fix(theme): mobile store banner
- replace SfButton with SfLink so we can have images inside elements without breaking hydration
- refactor(theme): change the way related and upsell products are loaded
- upsell/related products on the PDP will be now loaded onMounted hook
1. go to any page with prices
2. switch the currency
3. observe if price is recalculated according to the rates configured in magento
> fix(category): move products loading to onMount hook to avoid caching prices

- packages/api-client/src/helpers/apiClient/defaultSettings.ts
- packages/api-client/src/types/setup.ts
- packages/theme/composables/useApi/index.ts
- packages/theme/composables/useMagentoConfiguration.ts
- packages/theme/composables/useUiNotification/index.ts
- packages/theme/composables/useWishlist/index.ts
- packages/theme/helpers/integrationPlugin/index.ts
- packages/theme/middleware/checkout.ts
- packages/theme/middleware/is-authenticated.js
- packages/theme/middleware/is-authenticated.ts
- packages/theme/modules/magento/defaultConfig.ts
- packages/theme/modules/magento/helpers/index.ts
- packages/theme/modules/magento/plugin.ts
- packages/theme/plugins/__tests__/i18n.spec.js
- packages/theme/plugins/__tests__/token-expired.spec.js
- packages/theme/plugins/fcPlugin.ts
- packages/theme/plugins/i18n.ts
- packages/theme/plugins/token-expired.ts
Up until now we've had two cookie APIs: $cookies.get/set/remove and the vue-storefront/core provided $vsf.config.state.set[CookieName]. This PR removes all instances of the first API and makes them use the $vsf.config.state API
> refactor: unify cookie retrieval

- packages/theme/composables/useContent/index.ts
- packages/theme/composables/useContent/useContent.ts
The JSDoc examples of the `useContent` composable were using `export function {` instead of `export default {`, probably just a typo. I've fixed that and added space between import statements and the export in some examples.
`export function {` is a syntax error.
> docs: fix useContent JSDoc examples

- .github/workflows/deploy-vue-storefront-cloud.yml
After removal of secrets there's a problem where the theme is trying to find redis on the localhost host, but redis in VSF cloud is actually on the `redis` host
> fix: vsf cloud has no redis on localhost

- internals/eslint-vue/package.json
- package.json
- packages/theme/package.json
- yarn.lock
before:
after:
The leftover warnings require deeper changes/are more unsafe so I just wanted to push the easy ones for now
> chore: fix some "yarn install" peer dependency warnings

- packages/theme/middleware.config.js
- add imageProvider option value to the magento module
bugfix
manipulate VSF_IMAGE_PROVIDER env variable and observe if images are loaded properly for [ipx, cloudinary] at least
> fix: image provider options

- docs/.vuepress/config.js
- packages/api-client/src/api/categorySearch/categorySearch.ts
- packages/api-client/src/api/categorySearch/index.ts
- packages/theme/composables/index.ts
- packages/theme/composables/useCategorySearch/index.ts
- packages/theme/composables/useCategorySearch/useCategorySearch.ts
- **[BREAKING CHANGE]** Make the `error`, `loading` and `result` refs readonly;
- **[BREAKING CHANGE]** Rename `UseCategorySearch` interface to `UseCategorySearchInterface`;
- **[BREAKING CHANGE]** Rename `UseCategoryErrors` interface to `UseCategorySearchErrors`;
- Add type for the params object received by `UseCategorySearch.search` method;
- Write TSDocs for `categorySearch` API method and its GraphQL query;
- Write TSDocs for `useCategorySearch` composable and its types;
- Convert `useCategorySearch` and `categorySearch` into function declarations (since it's better for the docs generator);
- Export `useCategorySearch` types in `~/composables`.
https://vsf.atlassian.net/browse/M2-374
Improves the DX of the `useCategorySearch` composable.
> feat!: make `error`, `loading`, and `result` properties readonly on `useCategorySearch` composable

- packages/theme/lang/de.js
- packages/theme/lang/en.js
- packages/theme/pages/Product.vue
There was a "size guide" button on PDP. But we won't support the size guide (whatever it means) on the 1.0.0 page so I removed that button and translations from the code base.
> refactor: removed size guide

- docs/.vuepress/config.js
- packages/theme/composables/index.ts
- packages/theme/composables/useBilling/BillingDetails.ts
- packages/theme/composables/useBilling/index.ts
- packages/theme/composables/useBilling/useBilling.ts
- **[BREAKING CHANGE]** Make the `loading` and `error` ref readonly;
- **[BREAKING CHANGE]** Define a type for the `billingDetails` object received by the `save` method;
- Add types and interfaces for the `useBilling` composable;
- Write TSDoc comments for `useBilling` and its types;
- Change `useBilling` to function declaration (since it's better for the docs generator).
https://vsf.atlassian.net/browse/M2-374
Improves the DX of the `useBilling` composable.
> feat!: define a type for billingDetails and make refs readonly in the useBilling composable

- packages/theme/components/CartSidebar.vue
- packages/theme/components/Header/SearchBar/SearchResults.vue
- packages/theme/components/ProductsCarousel.vue
- packages/theme/composables/useProduct/index.ts
- packages/theme/enums/imageEnums.js
- packages/theme/modules/catalog/pages/category.vue
- packages/theme/pages/Checkout/Payment.vue
- packages/theme/pages/MyAccount/MyWishlist.vue
- packages/theme/pages/Product.vue
- add nuxt-img support on the cart and product page
- fix images proportions in all places where nuxt-img is used
Perf improvement
- visit a product page, cart, category etc
- make sure that cloudinary provider is enabled
- check images source in the page source
> feat: add more support for cloudinary images

- packages/theme/modules/catalog/pages/category.vue
- packages/theme/pages/Product.vue
We have not supported CDN for pages yet so for now we can remove cache-control settings.
> chore: removed cache-control settings from product and category page

- docs/.vuepress/config.js
- packages/theme/composables/index.ts
- packages/theme/composables/useUiNotification/index.ts
- packages/theme/composables/useWishlist/index.ts
- packages/theme/composables/useWishlist/useWishlist.ts
This PR updates the `useWishlist` composable:
* **[BREAKING CHANGE]** wraps the `loading` and `error` objects with `readonly` so they cannot be manipulated outside of the composable,
* improves typing,
* adds a short description to all interfaces, types, and properties.
> feat!: make `loading` and `error` properties readonly in the `useWishlist` composable

- packages/theme/composables/useCurrency/index.ts
- The change method of useCurrency is synchronous so it's not necessary to set the loading state there.
- customQuery was not passed correctly to API, and it's fixed, params type also is fixed
> refactor: refactored useCurrency `load` and `change` methods

- docs/.vuepress/config.js
- packages/api-client/src/api/requestPasswordResetEmail/index.ts
- packages/api-client/src/api/requestPasswordResetEmail/requestPasswordResetEmail.ts
- packages/api-client/src/api/resetPassword/index.ts
- packages/api-client/src/api/resetPassword/resetPassword.ts
- packages/theme/composables/index.ts
- packages/theme/composables/useForgotPassword/index.ts
- packages/theme/composables/useForgotPassword/useForgotPassword.ts
This PR updates the `useForgotPassword` composable
- [BREAKING CHANGE] make `useForgotPassword` properties readonly
- add JSDoc to API client's `resetPassword`
- add JSDoc to `requestPasswordResetEmail`
- add `useForgotPassword` JSDoc
> feat!: make `useForgotPassword` properties readonly

- packages/theme/components/AppHeader.vue
- packages/theme/composables/types.ts
- packages/theme/composables/useCart/useCart.ts
- packages/theme/getters/productGetters.ts
- packages/theme/getters/types.d.ts
- packages/theme/helpers/product/productData.ts
- packages/theme/modules/catalog/pages/category.vue
- packages/theme/pages/Home.vue
- packages/theme/types/core.d.ts
We don’t use the category getters. Each value of the category object is used directly in the template. If we need some additional logic around some of the fields let’s encapsulate it in composable. 
-
Perf improvement
-
> refactor: remove category getters call from app header

- docs/guide/configuration.md
- packages/theme/components/HeaderLogo.vue
- packages/theme/components/StoreSwitcher.vue
- packages/theme/components/StoreSwitcher/StoresModal.vue
- packages/theme/composables/useMagentoConfiguration.ts
- packages/theme/composables/useStore/index.ts
- packages/theme/layouts/default.vue
- packages/theme/nuxt.config.js
- packages/theme/plugins/query/StoreConfig.gql.ts
- packages/theme/plugins/storeConfigPlugin.ts
- move loading of the store config to the plugin
- add store config documentation
Perf improvement and better code base
-
> refactor: store config query

- packages/theme/composables/useCart/index.ts
- packages/theme/composables/useUser/index.ts
- packages/theme/composables/useUser/loginStatusPingQuery.gql.ts
- packages/theme/composables/useUser/useUser.ts
- packages/theme/layouts/default.vue
- packages/theme/pages/Checkout/UserAccount.vue
- packages/theme/pages/MyAccount.vue
- packages/theme/pages/MyAccount/MyNewsletter.vue
- packages/theme/pages/MyAccount/MyProfile.vue
- packages/theme/pages/MyAccount/MyWishlist.vue
- packages/theme/plugins/__tests__/token-expired.spec.js
- packages/theme/plugins/token-expired.ts
- packages/theme/stores/customer.ts
wait for: https://github.com/vuestorefront/magento2/pull/862
Currently the user/customer object is pretty big and is excessive for checking if the user is logged in. A simple boolean should be sufficient.
Now instead of loading the user in the default layout, the login status is calculated outside of vue in the token-expired plugin at the start of the application
Also fixed the logic in MyAccount.vue where it'd excessively query for the user/customer object
> perf!: load whole user object only when necessary

- .github/workflows/speedcurve.yml
Asks speedcurve to run a preformance test automatically after each PR is merged to develop
To verify if this works I've temporarily added a "on: push" to the workflow and it did work:
https://github.com/vuestorefront/magento2/runs/6037564073?check_suite_focus=true
Obviously I can't deploy as part of a PR so unfortunately this'll have to be merged and "we'll see" with the next deploy
> perf: request speedcurve pref test run after develop deployment

- docs/.vuepress/config.js
- packages/theme/composables/index.ts
- packages/theme/composables/useUserAddress/index.ts
- packages/theme/composables/useUserAddress/useUserAddress.ts
This PR updates the `useUserAddress` composable:
- [BREAKING CHANGE] wraps the `loading` and `error` objects with `readonly` so they cannot be manipulated outside of the composable,
- improves typing,
- adds a short description to all interfaces, types, and properties.
> feat!: make `error` and `loading` properties readonly on `useUserAddress` composable

- docs/.vuepress/config.js
- packages/api-client/src/api/setGuestEmailOnCart/index.ts
- packages/api-client/src/api/setGuestEmailOnCart/setGuestEmailOnCart.ts
- packages/theme/composables/index.ts
- packages/theme/composables/useGuestUser/index.ts
- packages/theme/composables/useGuestUser/useGuestUser.ts
This PR updates the `useGuestUser` composable:
- [BREAKIGN CHANGE] make properties readonly on `useGuestUser`
- add `setGuestEmailOnCart` JSDoc
- add JSDoc to `useGuestUser` composable
> feat!: make `error` and `loading` properties readonly in `useGuestUser` composable

- docs/.vuepress/config.js
- packages/api-client/src/api/availableStores/index.ts
- packages/theme/composables/index.ts
- packages/theme/composables/types.ts
- packages/theme/composables/useStore/index.ts
- packages/theme/composables/useStore/useStore.ts
This PR updates the `useStore` composable:
- [BREAKING CHANGE] wraps the `loading` and `error` objects with `readonly` so they cannot be manipulated outside of the composable,
- improves typing,
- adds a short description to all interfaces, types, and properties.
> feat!: make `error` and `loading` properties readonly on `useStore` composble

- packages/theme/components/AppHeader.vue
- packages/theme/components/CartSidebar.vue
- packages/theme/components/WishlistSidebar.vue
- packages/theme/composables/useWishlist/index.ts
- packages/theme/composables/useWishlist/useWishlist.ts
- packages/theme/getters/productGetters.ts
- fix issue with refreshig sidebar wishlist
- fix issue with wishlist sidebar transition
- fix issue with cart sidebar transition
#901
#898 
#536 
Bugfix
> fix: wishlist sidebar

- packages/theme/components/Hero.vue
- packages/theme/pages/Home.vue
https://vsf.atlassian.net/browse/M2-410
> feat: homepage - changed slider to hero section

- .eslintrc.js
- packages/theme/components/AppHeader.vue
- packages/theme/components/Header/Navigation/HeaderNavigation.vue
- packages/theme/components/Header/Navigation/HeaderNavigationItem.vue
- packages/theme/components/Header/Navigation/HeaderNavigationSubcategories.vue
- packages/theme/components/Header/Navigation/__tests__/HeaderNavigation.spec.js
- packages/theme/components/Header/Navigation/__tests__/HeaderNavigationItem.spec.js
- packages/theme/components/Header/Navigation/__tests__/HeaderNavigationSubcategories.spec.js
- packages/theme/components/__tests__/AddtoWishlist.spec.js
- packages/theme/package.json
- packages/theme/test-utils/mocks/categoryTreeDataMock.ts
- packages/theme/test-utils/mocks/useUiHelpersMock.ts
- yarn.lock
- add multilevel categories navigation
- add unit tests for new components
- upgrade @testing-library/user-event @13 -> @14
Improvement
> feat: header categories

- packages/theme/components/SkeletonLoader/index.vue
- packages/theme/modules/catalog/category/components/navbar/CategoryNavbar.vue
- packages/theme/modules/catalog/pages/category.vue
add skeleton loaders in category navbar
- Visit category page, execute any action eg. add filter
- Observe that skeletons are now masking loaded fields
> feat: add skeleton loaders in category navbar

- docs/package.json
- docs/yarn.lock
This PR updates VuePress to the latest 1.x version and adds the "--max-concurrency=32" parameter to the `build` script to fix broken builds
> docs: update vuepress and fix error during a build

- packages/theme/modules/catalog/pages/product.vue
make related and upsell products lazy loaded when visible
> perf: make related and upsell products lazy loaded when visible

- packages/theme/modules/catalog/pages/product.vue
perf: prevent loading all main images on the mobile PDP gallery
> perf: prevent loading all main images on the mobile PDP gallery

- packages/api-client/src/types/API.ts
- packages/theme/components/CouponCode.vue
- packages/theme/lang/de.js
- packages/theme/lang/en.js
- packages/theme/modules/checkout/composables/useCart/commands/applyCouponCommand.ts
- packages/theme/modules/checkout/composables/useCart/commands/removeCouponCommand.ts
- packages/theme/modules/checkout/composables/useCart/index.ts
- rework coupon code component to handle GraphQL errors
#957 
- add the product to the cart
- open the cart
- try to apply invalid coupon -> observe there are no errors in the console and the error message is verbose
- try to apply valid coupon -> observe that coupon was applied
- try to remove coupon -> observe the coupon was applied
- [ x] Bug fix (non-breaking change which fixes an issue)
> fix: coupon code invalid error message

- packages/theme/modules/catalog/category/components/views/CategoryProductGrid.vue
fix: category page - an equal amount of product for a row
#998
> fix: category page - equal amount of product for a row

- packages/theme/components/SkeletonLoader/index.vue
- packages/theme/modules/catalog/category/components/navbar/__tests__/CategoryNavbar.spec.js
- packages/theme/test-utils/mocks/categoryNavbarMock.ts
- packages/theme/test-utils/mocks/useUiHelpersMock.ts
- packages/theme/test-utils/mocks/useUiState.js
Added unit tests for packages/theme/modules/catalog/category/components/navbar/CategoryNavbar.vue
> test: categorynavbar component

- packages/theme/modules/catalog/product/components/product-types/bundle/BundleProduct.vue
- packages/theme/modules/catalog/product/components/product-types/configurable/ConfigurableProduct.vue
- packages/theme/modules/catalog/product/components/product-types/grouped/GroupedProduct.vue
- packages/theme/modules/catalog/product/components/product-types/simple/SimpleProduct.vue
- packages/theme/modules/catalog/product/composables/useProductGallery/index.ts
> fix: useProductGallery reactivity

- .vuestorefrontcloud/docker/docs/Dockerfile
- packages/theme/composables/useMagentoConfiguration/UseMagentoConfiguration.ts
- updated docs dockerfile
- fixed type issue in the euseMagentoConfiguration composable
> build: updated docs dockerfile and fix type issue

- packages/theme/package.json
- yarn.lock
I met some problems with graphql-request in the template-magento repository related to custom JSON parser introduced in 4.2.0 and to fix that I added graphql-request@4.1.0 as a dependency to be sure that everything works correctly.
> chore: updated graphql-request

- packages/theme/composables/types.ts
- packages/theme/lang/de.js
- packages/theme/lang/en.js
- packages/theme/modules/catalog/category/components/views/CategoryProductGrid.vue
- packages/theme/modules/catalog/category/components/views/CategoryProductList.vue
- packages/theme/modules/catalog/category/components/views/CategoryProductPrice.vue
- packages/theme/modules/catalog/category/components/views/useProductsWithCommonCardProps.ts
- packages/theme/modules/catalog/pages/category.vue
- packages/theme/modules/catalog/pages/product.vue
- packages/theme/modules/catalog/product/components/product-types/bundle/BundleProduct.vue
- packages/theme/modules/catalog/product/components/product-types/bundle/BundleProductSelector.vue
- packages/theme/modules/catalog/product/components/product-types/grouped/GroupedProductSelector.vue
- packages/theme/modules/catalog/product/getters/productGetters.ts
- packages/theme/modules/catalog/product/helpers/bundleProduct.ts
- fix the issue with displaying prices of PDP
- fix the issue with displaying prices of PLP
- fix calculation of prices for the bundle, grouped products
#973
> fix: issue with displaying product price od PDP and PLP

- docs/.vuepress/config.js
- docs/guide/filters.md
- packages/theme/modules/catalog/category/components/filters/CategoryFilters.vue
- packages/theme/modules/catalog/category/components/filters/FiltersSidebar/SelectedFilters.vue
- packages/theme/modules/catalog/category/components/filters/renderer/YesNoType.vue
- packages/theme/modules/catalog/category/components/filters/useFilters.ts
- packages/theme/modules/catalog/category/config/FiltersConfig.ts
- packages/theme/modules/catalog/category/config/__tests__/filtersConfig.spec.ts
- packages/theme/modules/catalog/category/config/config.ts
- filters can now be whitelisted
- update how yes_no filter is rendered on the applied filrer list
- update types for removable filters
- add docs for the filters managing
Improvement
> feat: add configurable filters

- packages/theme/modules/catalog/pricing/getGroupedProductPriceCommand.ts
- packages/theme/modules/catalog/product/components/product-types/grouped/GroupedProductSelector.vue
Actual behavior
The total price is calculated without including the special price of the first product - looks like the first product in the group is treated as a "normal" priced product.
Expected behavior
The total price is calculated correctly by using special prices associated with product.
Additional bug information
Reproduced with Chromium-based browsers (Chrome, Edge), Safari, and Firefox.
change grouped product options and observe if normal and special prices are calculated properly in the total result
> fix: grouped product special price calculation

- packages/theme/composables/types.ts
- packages/theme/modules/catalog/category/components/navbar/CategoryNavbar.vue
- packages/theme/modules/catalog/category/composables/useFacet/PerPageOptions.ts
- packages/theme/modules/catalog/category/composables/useFacet/index.ts
- packages/theme/modules/catalog/category/composables/useFacet/perPageOptions.ts
- packages/theme/modules/catalog/category/composables/useFacet/sortingOptions.ts
- packages/theme/modules/catalog/category/composables/useFacet/useFacet.ts
- packages/theme/modules/catalog/category/getters/facetGetters.ts
- packages/theme/modules/catalog/pages/category.vue
- packages/theme/modules/customer/pages/MyAccount/AddressesDetails/AddressesDetails.vue
Fix issue where AgnosticSort was totally different type than what would appear at runtime
> refactor: improve typing of sorting in facetGetters/category.vue

- packages/api-client/src/api/index.ts
- packages/api-client/src/api/route/index.ts
- packages/api-client/src/api/route/route.ts
- packages/api-client/src/api/urlResolver/index.ts
- packages/api-client/src/types/API.ts
- packages/theme/composables/useUrlResolver/UseUrlResolver.ts
- packages/theme/composables/useUrlResolver/index.ts
- packages/theme/modules/GraphQL/CategoryTreeRouteTypeguard.ts
- packages/theme/modules/catalog/pages/category.vue
THe urlResolver Magento query is deprecated on Magento API side. This PR:
- adds a new route query to the VSF API Client
- updates the useUrlResolver composable to use the new route query instead of depracated urlResolver query.
Refactorization
> refactor: refactored useUrlResolver to use the route query

- packages/theme/composables/useUiHelpers/index.ts
- packages/theme/composables/useUiHelpers/useUiHelpers.ts
- packages/theme/modules/catalog/category/components/pagination/CategoryPagination.vue
- packages/theme/modules/catalog/pages/category.vue
Filters are not taken off after when using pagination on the category page.
Bugfix
1. Go to Category Page (can be main or for given product type) - i. e. https://demo-magento2-dev.europe-west1.gcp.storefrontcloud.io/default/c/women/tops-women/jackets-women.html
2. Setup filter/category which should return > 10 products - i. e. Solid.
3. Hit Apply filters.
4. Switch to the second page of listed products.
> fix: m2-606. category page filters are take off after using pagination

- packages/theme/modules/catalog/category/helpers/__tests__/findActiveCategory.spec.ts
- packages/theme/modules/catalog/category/helpers/findActiveCategory.ts
Fix active category resolving in `useTraverseCategory`
Open "Men" category - https://demo-magento2-dev.europe-west1.gcp.storefrontcloud.io/default/c/men.html
> fix: m2-726. category page header invalid title

- docs/.vuepress/config.js
- docs/modules/catalog/filters.md
- docs/modules/catalog/product-types.md
Add docs for
- filters docs
- product types docs
> docs: add catalog module documentation

- packages/theme/modules/catalog/category/components/filters/CategoryFilters.vue
before this change on the category page, there were filters loading skeleton on mobile devices, but on mobile devices, filters can be visible only in overlay
After this change loader skeleton for filters on the category page is not visible anymore on mobile devices.
> fix: removed filters skeleton on mobile devices

- docs/composition/composables.md
When copying this document to our core docs, we noticed some typos.
> docs: fix typos in Composables document

- packages/api-client/src/api/customMutation/index.ts
- packages/api-client/src/api/customQuery/index.ts
- packages/api-client/src/types/API.ts
- packages/theme/components/TopBar/checkStoresAndCurrency.gql.ts
- packages/theme/composables/useApi/index.ts
- packages/theme/modules/catalog/category/components/cms/categoryContent.gql.ts
- packages/theme/modules/catalog/category/components/filters/command/getProductFilterByCategory.gql.ts
- packages/theme/modules/catalog/category/components/filters/renderer/CheckboxType.vue
- packages/theme/modules/catalog/category/components/filters/renderer/RadioType.vue
- packages/theme/modules/catalog/category/components/filters/renderer/YesNoType.vue
- packages/theme/modules/catalog/category/components/filters/renderer/__tests__/CheckboxType.spec.ts
- packages/theme/modules/catalog/category/components/filters/renderer/__tests__/RadioType.spec.ts
- packages/theme/modules/catalog/category/components/filters/renderer/__tests__/YesNoType.spec.ts
- packages/theme/modules/catalog/category/composables/useFacet/getFacetData.gql.ts
- packages/theme/modules/catalog/category/composables/useFacet/input/createProductAttributeFilterInput.ts
- packages/theme/modules/catalog/category/stores/graphql/categoryList.gql.ts
- packages/theme/modules/catalog/pages/category.vue
- packages/theme/modules/catalog/pricing/getPricesQuery.gql.ts
- packages/theme/package.json
- packages/theme/plugins/query/StoreConfig.gql.ts
refactor: refactor use api
- add graphql-tag
- remove count from filters
> refactor: m2-780. refactor use api

- packages/theme/components/CurrencySelector/CurrenciesModal.vue
- packages/theme/components/CurrencySelector/__tests__/CurrencySelector.spec.ts
- packages/theme/components/CurrencySelector/__tests__/currencyData.mock.ts
- packages/theme/test-utils/mocks/useCurrency.ts
> test: useCurrency unit tests

- packages/api-client/src/api/addProductsToCart/addProductsToCart.ts
- packages/api-client/src/types/API.ts
- packages/theme/modules/catalog/product/components/product-types/bundle/BundleProductSelector.vue
- packages/theme/modules/catalog/product/components/product-types/configurable/ConfigurableProduct.vue
- packages/theme/modules/catalog/product/components/product-types/grouped/GroupedProductSelector.vue
- packages/theme/modules/catalog/product/components/product-types/simple/SimpleProduct.vue
- packages/theme/modules/catalog/product/components/product-types/styles.scss
- packages/theme/modules/checkout/composables/useCart/commands/addItemCommand.ts
- packages/theme/modules/checkout/composables/useCart/index.ts
add quantity error message on the PDP when adding to the cart
#1013 
1. Open any product page.
2. Add more items than available quantity - `100` or `200` should be enough.
3. Hit "Add to cart" button.
4. Repeat for all types of products.
> feat: add quantity error message on the PDP when adding to the cart

- packages/theme/lang/de.js
- packages/theme/lang/en.js
- packages/theme/modules/customer/composables/useUser/index.ts
Toast with an error message should show up instead of success toast.
1. log in to your account.
2. Hit the Account icon I top navigation.
3. Go to password change.
4. Input the wrong current password.
5. Input a new password.
6. Hit Update Password.
> fix: m2-593. my account password change toast fix

- packages/theme/helpers/cart/addToCart.ts
From now when the user adds to the cart grouped product on the category page, VSF will redirect to the product page and add the possibility to select grouped product options.
> fix: m2-705. fixed adding grouped product to cart from catalog

- packages/theme/modules/customer/pages/MyAccount/OrderHistory/SingleOrder/SingleOrder.vue
Redirect to the order history page when single order does not exist in a store.
> fix: fixed order details 500 error

- packages/theme/modules/catalog/pages/category.vue
before this commit, the page number remained unchanged after changing filters
this was as problem in the scenario where:
1. open the category Women - it has 8 pages by default
2. go to page 8
3. apply some filter - eg. select "Capri" in the Material section
4. the `yarn dev` console where nuxt is running will report errors like
"currentPage value 8 specified is greater than the X page(s) available"
you can't know how many pages a filter will return so always returning
to first page makes sense
this also works ok if no products are returned
> fix: move user to first page of products after applying filters

- packages/theme/modules/checkout/composables/useCart/commands/addItemCommand.ts
Before this PR, configurable product's selected options were not displayed on cart and checkout
After this PR, configurable product's selected options are displayed in the mini cart and checkout
M2-860
> fix:  cart, checkout - size and colour values are wrongly dispayed

- packages/theme/modules/catalog/category/components/navbar/CategoryNavbar.vue
- packages/theme/modules/catalog/category/components/views/CategoryProductGrid.vue
- packages/theme/modules/catalog/pages/category.vue
1. Fix last element in first row sometimes being larger than other items
2. Fix "Filters" button being offscreen on a 320px wide viewport
3. Also fix product category sometimes being wider than the viewport iteslf
> fix(category): fix various rwd issues on category mobile view

- packages/theme/modules/checkout/components/UserBillingAddresses.vue
- packages/theme/modules/checkout/components/UserShippingAddresses.vue
- packages/theme/modules/checkout/components/styles/userAddresses.scss
Before this PR user addresses styles on checkout were fixed only on the shipping step. 
I realized that the SCSS code was duplicated for the shipping and billing step so I moved the SCSS code to a separate file. 
I changed class names (they are scoped so we don't need to use prefixes like .shipping__addresses or .billing__adresses.) to use simpler classes like .addresses and .address. 
Now styles for addresses in shipping and billing steps are correct and the code is not duplicated anymore.
M2-709
> refactor:  user addresses styling

- packages/theme/modules/checkout/pages/Checkout/UserAccount.vue
- packages/theme/modules/customer/components/LoginModal/LoginModal.vue
- packages/theme/modules/customer/components/LoginModal/__tests__/LoginModal.spec.ts
- packages/theme/modules/customer/composables/useUser/index.ts
Before this commit, useUser().register error path used useUiNotification().sendNotification,
but useUser().login's error path did not. UserAccount.vue used sendNotification
aswell on its own side.
So when login() errored (bad password etc.) the useUser().login didn't
send notifications, but UserAccount.vue - further down the pipeline - did.
The contrary happened in register() - both UserAccount.vue and
register() sent notifications.
So I had to make a decision - either add sendNotification to
useUser().login the same way as in register, AND remove the
UserAccount.vue notifications
or
remove notifications from the composable and just handle it in
UserAccount.vue itself.
We decided on option 1 with Marcin.
M2-753
> fix: unify login/register notifications and error handling

- packages/theme/modules/customer/composables/useUser/index.ts
Before this PR,  the App crashed during merging carts with bundled products.
This is caused by an internal error in Magento 2.4.3 and 2.4.4.
On the Magento 2.4-dev branch, it works as well so probably it will work in Magento 2.4.5
For now, I just handled errors thrown by mergeCarts mutation.
After this PR it's possible to log in when you have bundled product in the cart. The app doesn't crash anymore.
> fix: m2-861 - merging cart doesn't work for bundled products

- packages/theme/helpers/checkout/address.ts
- packages/theme/modules/checkout/components/UserBillingAddresses.vue
- packages/theme/modules/checkout/components/UserShippingAddresses.vue
- packages/theme/modules/checkout/pages/Checkout/Billing.vue
- packages/theme/modules/checkout/pages/Checkout/Shipping.vue
- packages/theme/modules/customer/getters/userBillingGetters.ts
I refactored the Checkout and Billing pages a bit because it's the 2nd time something is returing from a retest and I was tired of the outdated logic in those components.
1. addressId are now always numbers (that's how they come from the api). String casts are used only when a function somewhere deeper down the line needs it
2. simplify logic of detecting whether the default address should be preselected. Preselection should only happen if a shipping/billing address weren't previously set on the cart. The logic from before PR doesn't quite work since the form approach changed since then
3. Make  UserBillingAddresses use two way binding for selecting the address, rather than an internal computed. This re-introduces the behavior seen in M2-333 but that's intended
4. Show country name …
> refactor(checkout): simplify billing/checkout logic

- packages/theme/modules/catalog/product/components/product-types/configurable/ConfigurableProduct.vue
- packages/theme/modules/checkout/composables/useCart/commands/addItemCommand.ts
- packages/theme/modules/checkout/composables/useCart/index.ts
- packages/theme/modules/checkout/composables/useCart/useCart.ts
Before this PR, the last option of configurable was added to the cart instead of the option selected by the user.
M2-860
> fix:  fixed wrong values of selected configurable product variants

- packages/theme/components/Header/Navigation/HeaderNavigationSubcategories.vue
Before this PR mega menu was covered by my account content in safari
After this PR, content doesn't cover the mega menu
> fix: m2-618. fixed mega menu z-index in safari

- packages/theme/components/SkeletonLoader/index.vue
- packages/theme/modules/catalog/category/components/filters/CategoryFilters.scss
- packages/theme/modules/catalog/category/components/filters/CategoryFilters.vue
- packages/theme/modules/catalog/category/components/filters/renderer/CheckboxType.vue
- packages/theme/modules/catalog/category/components/filters/renderer/RadioType.vue
- packages/theme/modules/catalog/category/components/filters/renderer/SwatchColorType.vue
- packages/theme/modules/catalog/category/components/filters/renderer/YesNoType.vue
- packages/theme/modules/catalog/category/components/views/CategoryProductGrid.vue
- packages/theme/modules/catalog/category/components/views/CategoryProductList.vue
- packages/theme/modules/catalog/pages/category.vue
> perf: category page CLS improvement

- packages/theme/modules/checkout/getters/cartGetters.ts
- packages/theme/modules/checkout/pages/Checkout/Payment.vue
checkout discounted price is wrongly displayed
Given: prices sum of all products in user cart has to be > 200$.
1. Go to checkout.
2. Proceed to Payment section.
> fix: checkouts discounted price is wrongly displayed

- packages/theme/components/AppHeader.vue
- currency and store switcher will no behave in the same way on the desktop and the mobile
bugfix
1. go to https://demo-magento2-canary.europe-west1.gcp.storefrontcloud.io/default
2. create account
3. add shipping address in user settings and set it as default
4. add product to cart and proceed to chekout
5. try to select shipping method
> fix: empty list of currencies while trying to change currency

- packages/theme/components/CartSidebar.vue
- disable more-actions for all views on the cart
1. Add any product to cart.
2. Open cart.
> fix: m2-703. cart three dots icon on mobile view

- packages/theme/modules/customer/pages/MyAccount/OrderHistory/SingleOrder/SingleOrder.vue
- add proper encoding in the customer order history
-
1. Buy any product with special signs, i. e. "Pursuit Lumaflex™ Tone Band".
2. Go to "My account" -> "Order history".
3. Open details of last order.
> fix: m2-839. product names with special signs are wrongly encoded

- packages/api-client/src/api/productDetail/productDetailsQuery.ts
- packages/theme/modules/catalog/pages/product.vue
- packages/theme/modules/catalog/product/queries/getProductPriceBySku.gql.ts
The second part of https://github.com/vuestorefront/magento2/pull/1146
Before this PR, prices were not recalculated properly for configurable products.
Reason: prices for product variants were cached in Redis. 
After this PR prices are recalculated properly for configurable products. 
I moved loading data of variants from a query that is run on server-side (`packages/api-client/src/api/productDetail/productDetailsQuery.ts`) to the query that is run on client-side (`packages/theme/modules/catalog/product/queries/getProductPriceBySku.gql.ts`)
M2-668
> fix!: m2-668 fixed price recalculation for configurable products

- packages/theme/lang/de.js
- packages/theme/lang/en.js
- packages/theme/modules/checkout/components/UserBillingAddresses.vue
- packages/theme/modules/checkout/components/UserShippingAddresses.vue
- packages/theme/modules/checkout/composables/useShipping/index.ts
- packages/theme/modules/checkout/pages/Checkout/Billing.vue
- packages/theme/modules/checkout/pages/Checkout/Shipping.vue
Shipping address - behavior on the checkout:
- link ‘Use this address as my default one’ should not be displayed
- headings of the sections are displayed for selecting address and entering new address (see attached preview for the reference)
- when a user adds a new address using the form, it shouldn’t be saved in the address book
Billing address - behavior on the checkout:
- if there is not default billing address in address book, no one address should be selected on billing step
- if there is a default billing address in the address book, it should be selected on the billing step
- link ‘Use this address as my default one’ should not be displayed
- when a user adds a new address using the form, it shouldn’t be saved in the address book
> feat: update behaviour of the addresses on the checkout

- README.md
- docs/installation-setup/installation.md
- packages/api-client/README.md
- packages/composables/README.md
Installation command that was described `vsf init` has been depracated so our docks was not up tom date
We updated the readme files and installation guide to use `npx @vue-storefront/cli generate store` so the documentation is up to date.
> docs: updated installation guide

- packages/theme/modules/catalog/product/getters/productGetters.ts
When it was more than four images in the gallery, the layout of PDP was broken:
There can max four items in the product gallery
**Note**: I know it's not a perfect solution, but because of Storefront UI constraints, I don't have a better idea for now. 
We need to wait until it is fixed in SFUI.
> fix: added limit for product gallery size

- .github/workflows/deploy-vue-storefront-cloud.yml
the current middleware url getting logic can be moved to the already existing block
(still have to check if it works)
> ci: simplify getting middleware url

- packages/theme/modules/catalog/category/helpers/useTraverseCategory.ts
this commit was made because if you went to a category and changed to
the 2nd page, the currently active category's name would not appear
after hard refreshing the page
this was happening because activeCategory used route.value.fullPath,
which includes the query params. So after the regex pipeline from
urlPathToFind, the value passed to findActiveCategory() was
"men?page=2" (expected query-param free "men")
it was possible to fix this by adding another regex to the pipeline but
it's cleaner to just use route.value.path as that's the intention of the implementation
M2-1035
> fix: don't inclue query params in urlPathToFind

- packages/theme/modules/catalog/pages/category.vue
before this commit pagination arrows on the category page would be
hidden if you hard refreshed the page
the culprit was the on-interaction prop on the LazyHydrate component
M2-1034
> fix: show pagination arrows after category refresh

- packages/theme/modules/catalog/product/components/product-types/styles.scss
Product gallery thumbs had wrong with on PDP in Safari browser.
Product gallery thumbs have the correct width in the Safari browser.
> fix: images in product gallery are overlayed with main image

- packages/theme/helpers/integrationPlugin/_proxyUtils.ts
Removed getBaseUrl function that is unnecessary once we added VSF_MIDDLEWARE_URL env variable.
> build!: removed getBaseUrl function from proxyUtils

- .github/workflows/deployment-template.yml
Before this PR, we just waited for 5 minutes in CD before marking a deployment as succeded hoping Farmer bootstrapped our app pod during that time. After this PR, we poll Farmer to check if it's ready yet - this is less failure prone.
The result is that Farmer usually deploys the pod in 2-3 minutes rather than 5, and our speedcurve tests should give us more confidence since now we're sure we're running tests on a fresh pod.
> ci: poll farmer for pod deployment status

- packages/theme/package.json
- yarn.lock
- lock dependencies on the last working version to avoid upgrade issues
> fix: update vue dependencies

- packages/theme/pages/Home.vue
Previously, static images were lacking the extension and it was not possible to load them properly with a nuxt-image in the static mode.
- add images extensions for a proper rendering
#1291
> fix: images are not loaded properly with ipx

- .github/workflows/deploy-vue-storefront-cloud.yml
our approach to reporting deployment status changed so we no longer need
the personal access token workaround. In the past, it was needed because
the deploy-template.yml workflow was called by the parent
deploy-vue-storefront-cloud workflow, which is prevented by:
https://github.com/chrnorm/deployment-action/tree/3afecce166a0a2f92d3a9e7351a9908a72121c24#notes
using a personal access token is also not secure since if stolen it
could be used to push to the deployment status of every repo I have
access to (including vsf org).
> ci: stop using personal access token for deployment api

- docs/installation-setup/configure-magento.md
Command correction as per markshust script
https://github.com/vuestorefront/magento2/issues/1096
> fix: command correction according to markshust script

- packages/theme/nuxt.config.js
i18n is responsible for basic SEO optimization including canonical URLs, it can be configured manually but I added VSF_STORE_ENV as a base URL which will be a good OOB solution for most projects.
Improvement
> feat: add i18n base url configuration

- packages/theme/modules/customer/pages/MyAccount/AddressesDetails/AddressEdit.vue
- packages/theme/modules/customer/pages/MyAccount/AddressesDetails/AddressNew.vue
- packages/theme/modules/customer/pages/MyAccount/AddressesDetails/AddressesDetails.vue
- packages/theme/modules/customer/pages/MyAccount/MyNewsletter.vue
- packages/theme/modules/customer/pages/MyAccount/MyReviews.vue
- packages/theme/modules/customer/pages/MyAccount/MyWishlist.vue
- packages/theme/modules/customer/pages/MyAccount/ResetPassword.vue
- packages/theme/modules/customer/pages/styles/shared.scss
remove style duplication in my account route components
Refactoring
-
> refactor: remove style duplication in my account route components

- packages/theme/components/Header/Navigation/HeaderNavigation.vue
Description
If the value passed to Boolean is an empty array it will always return true.
Related Issue
https://github.com/vuestorefront/magento2/issues/1207
Types of changes
[x ] Bug fix (non-breaking change which fixes an issue)
New feature (non-breaking change which adds functionality)
Breaking change (fix or feature that would cause existing functionality to change)
Checklist:
[ x] My code follows the code style of this project.
> fix: header navigation "hasChildren" always returning true

- packages/api-client/src/api/getAvailableShippingMethods/GuestAvailableShippingMethods.ts
Replace a cart_id getAvailableShippingMethods query variable with a cartId
fix #1264
> fix: getAvailableShippingMethods query variables

- .github/workflows/deploy-vue-storefront-cloud.yml
- .github/workflows/public_env_info/canary
- .github/workflows/public_env_info/dev
- .github/workflows/public_env_info/enterprise
- .github/workflows/public_env_info/production
- .github/workflows/run-k6-load-test.yml
Change K6 action so that it works by picking the environment rather than specifying the url. Our upcoming implementation of load tests will have three separate urls (magento instance, middleware url, frontend url). Specifying each url by hand/adding it to the url dropdown would be annoying
> ci: refactor k6 action to add new env vars

- .github/workflows/deploy-vue-storefront-cloud.yml
Fixes https://github.com/vuestorefront/magento2/runs/7629131018?check_suite_focus=true not working
The cause was the code wasn't checked out (job results aren't shared)
> ci: fix code not checked out

- packages/theme/modules/checkout/composables/useCart/commands/addItemCommand.ts
Fix a copy/paste code when code was copy but a variable didn't replace. Replace downloadableProduct
with virtualProduct in the add item to cart command for case VirtualProduct.
fix #1323
> fix: downloadableProduct might not have been initialized

- docs/migration-guides/1.0.0/index.md
Fixed wrong link to the BIC document
> docs: fixed breaking change reference link

- packages/theme/modules/customer/pages/MyAccount/AddressesDetails/AddressForm.vue
User cannot edit the address after switching from a country with state/province to non-state/province country 
#1343 
1. Login.
2. Go to My Account.
3. Visit Address Details.
4. Add new address in country with provinces/states.
5. Save the address.
6. Hit Change button.
7. Change country to one without provinces/states in the dropdown i. e. Malta.
8. Save the address.
9. Open it one more time and try to edit some field or setup this address as a default for shipping or billing.
10. Save.
> fix: m2-938 fix issue with a store switching on the customer account

- packages/theme/modules/catalog/pages/category.vue
- packages/theme/modules/catalog/pages/product.vue
Before this PR product was not marked as added to the wishlist on the PDP and PLP. Now wishlist will be loaded on both pages to fetch the data required for evaluation if the product is added to the wishlist. 
bugfix
1. Login.
2. Open the product detail page.
3. Move the mouse on "Add to wishlist" and click it.
4. Refresh the page.
5. Go back to the product list page where the product is displayed.
6. Move mouse on product preview of product added to wishlist.
> fix: m2-941 product is not marked as added to the wishlist

- packages/theme/modules/customer/pages/MyAccount/MyAccount.vue
- packages/theme/modules/customer/pages/MyAccount/useSidebarLinkGroups.ts
Logout should work always, also after page refresh during browsing "My Account".
Open Magento 2 e-commerce integration page.
2. Login using valid credentials.
3. Move the mouse to the "User Account" icon in the top menu bar and click it.
4. Refresh the page.
5. Move the mouse to "Logout" in the left column and click it.
> fix: m2-1017 logout doesn't work after reload of the MyAccount page

- packages/theme/modules/catalog/pages/category.vue
Product List Page, Product Detail Page - App is unresponsive after hard refreshing the page as a logged in user
Open any Product List Page.
2. Change store to "German".
3. Change currency to "PLN" or "EUR".
4. Switch store to default one.
5. Refresh the page.
> fix: m2-930 product list page is sometimes unresponsive after the store switch

- packages/api-client/src/api/customerOrders/customerOrders.ts
- packages/theme/modules/checkout/getters/orderGetters.ts
- packages/theme/modules/customer/pages/MyAccount/OrderHistory/OrderHistory.vue
- packages/theme/modules/customer/pages/MyAccount/OrderHistory/SingleOrder/SingleOrder.vue
- packages/theme/plugins/fcPlugin.ts
- rework deprecated grand_total from the customerOrders query
- make prices and currency constant in the customer dashboard
- [**Breaking Change**] To display the order's value properly it was necessary to get rid of the old base_price from the query because it was deprecated and use the current base price from the totals.
- There is no way to successfully switch currency for the order in the customer dashboard because rates are not saved once the order is placed. Therefore, we should always display the currency and the base price of the order when it was placed. As a result, orders placed in EUR will be always displayed in EUR without any rate calculations.
#1342
Given: user with orders in the German store.
1. log in to the German store.
2. Click "My account" icon in the top navbar.
3. …
> fix!: displaying proper price and currency in the customer dashboard

- packages/theme/modules/core/GoogleFontsAPI/probeGoogleFontsApi.ts
- packages/theme/nuxt.config.js
If **https://google-webfonts-helper.herokuapp.com/api** is not responsive, the plugin will be omitted and appropriate information will be logged in the console. Before this PR, if the GoogleFontAPI, Heroku CDN, or any intermediate service were down, the app could not build properly.
> feat: add a buildtime google font api probe mechanism

- docs/installation-setup/configure-magento.md
Once we remove graphql-request and do not send requests to Magento directly from the front end, we can remove information about CORS configuration from the installation guide.
Keep docs up to date
I tested docs on my local
> docs: removed outdated information about cors configuration

- packages/theme/nuxt.config.js
Checkout - CDN is serving cached data for checkout
- exclude */customer*, */checkout* paths from being cached in the CDN
Cache headers were validated on the customer account and the checkout
> fix: update CDN default configuration

- packages/theme/composables/useImage/index.ts
Fix that will resolve the following error.
```
ERROR Cannot read properties of null (reading 'split')
at a.getMagentoImage (composables/useImage/index.ts:48:31)
at 65.js:6481:379
at a.ve [as _l] (/var/www/node_modules/vue/dist/vue.runtime.common.prod.js:6:15953)
at a.GroupedProductSelectorvue_type_template_id_59640822_render (modules/catalog/product/components/product-types/grouped/GroupedProductSelector.vue)
at /var/www/node_modules/@vue/composition-api/dist/vue-composition-api.common.prod.js:16:13873
at qt (/var/www/node_modules/@vue/composition-api/dist/vue-composition-api.common.prod.js:16:13228)
at a.r.render (/var/www/node_modules/@vue/composition-api/dist/vue-composition-api.common.prod.js:16:13844)
at a.t._render (/var/www/node_modules/vue/dist/vue.runtime.common.prod.js:6:35346) …
```
> fix: getMagentoImage reading 'split' error

- packages/theme/modules/catalog/pages/category.vue
- packages/theme/modules/catalog/product/getters/productGetters.ts
1. Visit M2 integration app.
2. Clear cache.
3. Open any category page.
4. Open any product detail page.
5. Go back using native, browser back button.
6. Switch to different category.
or simply jump between Gear and Man categories.
> fix: product list page items on product page list page zero prices issues

- packages/api-client/src/api/productDetail/productDetailsQuery.ts
- packages/theme/lang/de.js
- packages/theme/lang/en.js
- packages/theme/modules/catalog/product/components/product-types/grouped/GroupedProductSelector.vue
Product Detail Page - 500 after refreshing the product detail page of the grouped product
1. Visit M2's integration page - DEV.
2. Go to "Gear".
3. Open PDP of "Set of Sprite Yoga Straps".
4. Refresh the page.
5. Observe that the product is loaded properly
> fix: ssr reload on the grouped product page

- packages/theme/modules/catalog/product/components/product-types/styles.scss
The product detail gallery is missing when browsing products using mobile chromium-based browsers
1. Visit M2 integration app using chromium based mobile browser (Chrome or Samsung Internet).
2. Go to any product with image gallery, e. g. https://magento2stage.vuestorefront.io/default/erika-running-short.html
3. Observe that the gallery is now visible
> fix: product detail gallery is missing when browsing products using mobile

- packages/theme/components/CartSidebar.vue
Fix the issue: 
1. Visit M2 integration app as a guest.
2. Click cart icon in top navigation.
```
Following error occurs in the console:
`TypeError: Cannot read properties of null (reading 'id')
at CartSidebar.vue?b5dd:364:23
at f.<anonymous> (vue-composition-api.mjs:1125:23)
at ee (vue.runtime.esm.js:1863:57)
at vn (vue.runtime.esm.js:4235:7)
at Object.insert (vue.runtime.esm.js:3158:7)
at j (vue.runtime.esm.js:6390:28)
at f.__patch__ (vue.runtime.esm.js:6609:5)
at t._update (vue.runtime.esm.js:3963:19)
at f.r (vue.runtime.esm.js:4081:10)
at En.get (vue.runtime.esm.js:4495:25)
```
I was no longer able to reproduce the issue following the steps in the description.
> fix: cart type error in the console after opening mini cart as a guest

- packages/api-client/src/api/productDetail/productDetailsQuery.ts
Remove `stock_status` and `only_x_left_in_stock` fields from `productDetailsQuery`.
This PR is related to #834.
> fix: remove `stock_status` and `only_x_left_in_stock` fields from `productDetailsQuery`

- docs/index.md
Fixes demo links formatting. It appears this issue might have been caused by Prettier in someone's local dev env?
- fix formatting on `docs/index.md` (the home page)
> docs: fix demo links

- packages/api-client/package.json
- packages/api-client/src/api/productDetails/index.ts
- packages/api-client/src/api/products/index.ts
When a product is not found it results in a 500. This should result in a 404, or perhaps still a 200. But 500 is not correct in any case.
- refactor product fetch endpoints to return 200 instead of 500 when no products found
closing [IN-3282](https://vsf.atlassian.net/browse/IN-3282)
[IN-3282]: https://vsf.atlassian.net/browse/IN-3282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: products fetch http codes change

- .changeset/clever-ducks-chew.md
- packages/api-types/src/Api.ts
Error
[GraphQL error]: Message: Variable "$cartId" got invalid value {"cartId":""}; String cannot represent a non string value: {"cartId":""}, Location: [column: 36, line: 1], Path: undefined
How to reproduce:
Go through the checkout process. Once you get to the payment selection part of the process you will see that it freezes in the UI and you get the error in the console. 
closing [https://vsf.atlassian.net/browse/IN-3771](https://vsf.atlassian.net/browse/IN-3771)
> fix: get available payment methods type

- docs/content/2.getting-started/2.magento.md
N/A
Providing some more details in how to generate access keys, added/updated link to the guide. Small wording changes.
> chore: Update links to access keys guide

- .changeset/random-name-tg.md
- packages/api-client/src/types/context.ts
In extensions in `beforeCall` hook, we're able to override the `configuration`. However it's not possible to add typing for it. Having an IntegrationContext as interface would allow user to use the declaration merging.
> chore: change context type to interface

- .changeset/little-bottles-switch.md
- packages/api-client/src/api/addBundleProductsToCart/addBundleProductsToCart.ts
- packages/api-client/src/api/addBundleProductsToCart/index.ts
- packages/api-client/src/api/addConfigurableProductsToCart/addConfigurableProductsToCart.ts
- packages/api-client/src/api/addConfigurableProductsToCart/index.ts
- packages/sdk/__tests__/integration/__config__/customQueries/addBundleProductsToCart/index.ts
- packages/sdk/__tests__/integration/__config__/customQueries/addConfigurableProductsToCart/index.ts
- packages/sdk/__tests__/integration/__config__/customQueries/jest.customQueries.ts
- packages/sdk/__tests__/integration/__config__/jest.const.ts
- packages/sdk/__tests__/integration/__nock-fixtures__/[SDK][Integration-Tests]-addBundleProductsToCart-should-add-product-to-cart
- packages/sdk/__tests__/integration/__nock-fixtures__/[SDK][Integration-Tests]-addBundleProductsToCart-should-add-product-to-cart-and-return-custom-query-fields
- packages/sdk/__tests__/integration/__nock-fixtures__/[SDK][Integration-Tests]-addConfigurableProductsToCart-should-add-product-to-cart
- packages/sdk/__tests__/integration/__nock-fixtures__/[SDK][Integration-Tests]-addConfigurableProductsToCart-should-add-product-to-cart-and-return-custom-query-fields
- packages/sdk/__tests__/integration/addBundleProductsToCart.spec.ts
- packages/sdk/__tests__/integration/addConfigurableProductsToCart.spec.ts
- packages/sdk/__tests__/unit/addBundleProductsToCart.unit.spec.ts
- packages/sdk/__tests__/unit/addConfigurableProductsToCart.unit.spec.ts
- packages/sdk/src/methods/addBundleProductsToCart/index.ts
- packages/sdk/src/methods/addConfigurableProductsToCart/index.ts
- packages/sdk/src/methods/index.ts
closing https://alokai.atlassian.net/browse/ES-159
> feat: add configurable/bundle products to cart

- docs/content/2.getting-started/1.quick-start.md
- docs/content/2.getting-started/3.supported-features.md
- docs/content/3.basics/1.products.md
- docs/content/3.basics/2.cart.md
- docs/content/3.basics/3.authenthication.md
- docs/content/3.basics/4.users.md
- docs/content/3.basics/5.wishlist.md
- docs/content/3.basics/6.checkout.md
- docs/content/3.basics/7.misc.md
- docs/content/4.advanced/custom-queries.md
Document usage of middlewareModule with Magento 2 integration
> docs: document usage of middlewareModule with Magento 2 integration

- .changeset/ninety-parents-trade.md
- packages/api-client/src/index.ts
> fix: missing endpoints type export

- .changeset/grumpy-eels-care.md
- packages/api-client/package.json
- packages/api-client/src/api/cmsPage/index.ts
- packages/api-client/src/api/productDetails/index.ts
- packages/api-client/src/api/products/index.ts
- packages/api-client/src/api/requestPasswordResetEmail/index.ts
- packages/api-client/src/api/resetPassword/index.ts
- packages/api-client/src/helpers/magentoLink/graphQl.ts
- packages/api-client/src/helpers/magentoLink/index.ts
- packages/api-client/src/helpers/magentoLink/linkHandlers.ts
- packages/api-client/src/index.server.ts
- yarn.lock
[IN-4412](https://alokai.atlassian.net/browse/IN-4412)
[IN-4412]: https://alokai.atlassian.net/browse/IN-4412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(in-4412): logger in magento api
